### ISSUE TITLE
CKEditor caption text should wrap

### ISSUE THREAD

**Issue by jenlampton** [backdrop/backdrop-issues#1200]
If my caption is wider than the image its on, the caption text should wrap, and the "box" around the image should only be as wide as the image itself.

![screenshot27](https://cloud.githubusercontent.com/assets/100206/9921868/9bf91e3c-5c9f-11e5-801c-795dc912cb41.png)

---

PR by @quicksketch: https://github.com/backdrop/backdrop/pull/1959

**Comment by quicksketch** [comment]
We could use a screenshot here, though I've seen what you're talking about.

**Comment by quicksketch** [comment]
Hm, I swear that https://github.com/backdrop/backdrop/issues/1068 solved this problem, but now it's not having an effect. We'll need to come up with different solution.

**Comment by quicksketch** [comment]
I've reverted https://github.com/backdrop/backdrop/pull/1068 for the time being. This problem is really quite difficult.

I tried all the solutions listed at http://stackoverflow.com/questions/23160267/ie-element-width-to-min-content, but none of them are fully responsive. Maybe the insight of @wesruv might be able to suggest something the Internet hasn't thought of yet.

**Comment by wesruv** [comment]
Yeeeaaaahhh, I think this is the same issue as fieldsets not enforcing max width. I might need help replicating this, but I'll give 'er a go.

**Comment by wesruv** [comment]
Nope completely different thing :stuck_out_tongue: 

I haven't tried doing something quite like this before, I'd usually `float` the `figure` element, and I think the caption would behave better inside a floated element. 

*But* if we prefer more of an `inline-block` type layout, then `display: table` should work better, since `inline-block` is more `inline` than it is `block` :angry: 

So I made the figure `display: table` and the caption is `display: table-caption` and it seems to behave properly. Didn't know that table-caption existed until Chrome suggested it in dev tools, lol.

PR here: https://github.com/backdrop/backdrop/pull/1070

@quicksketch fwiw, I couldn't replicate the bug until I pulled the revert commit, but I think these styles will behave a little better (knocks on wood).

**Comment by quicksketch** [comment]
> So I made the figure display: table and the caption is display: table-caption and it seems to behave properly. Didn't know that table-caption existed until Chrome suggested it in dev tools, lo

Hey @wesruv. I think I tried this particular combination, but the figure element stopped being responsive. That is, when scaling the window down, the figure sticks out the side of the viewport instead of shrinking down. I suppose that makes sense because a "table" doesn't shrink down when its contents are too big either.

**Comment by wesruv** [comment]
I'm pretty sure I can fix that... I will give it a shot tomorrow

**Comment by wesruv** [comment]
BLARG! Why is this hard! This should not be :angry: 

I'm not seeing a good CSS solution that'll work in all browsers.

I think the best route would be to set a `width` on the `figure` element based on the image's width. Then we'll have what we need to lay this out properly.

Here's a codepen of what I'm thinking:
Code & Demo: http://codepen.io/wesruv/pen/rOeppZ?editors=110
Full page demo: http://codepen.io/wesruv/full/rOeppZ/

It'd be coolest if we could make this happen on the backend instead of using JS, but JS wouldn't be bad.

Postscript.
IMO `max-width` should work on table's, but the W3C disagrees because of our blood vendetta.

**Comment by quicksketch** [comment]
> BLARG! Why is this hard! This should not be :angry: 

I know! :banana:

> I think the best route would be to set a width on the figure element based on the image's width. 
> It'd be coolest if we could make this happen on the backend instead of using JS, but JS wouldn't be bad.

We already have a filter that is adding the wrapper, so this is entirely possible. It's also themeable, so if you seriously disagreed with the idea, you could undo it.

I think this is the best idea. Although using an inline style is "offensive" it also seems to be the only possible solution. In truth it is only a little worse than the "width" attribute on the img tag itself. We also ended up having to do something similar to this for dialogs, where they have a hard-coded width of "100%" but you have to use max-width to restrict them down if desired. Okay. Maybe it's not the same. But sometimes you just have hard decisions and choose the least of several evils.

**Comment by wimleers** [comment]
Together with @quicksketch, we ended up using the `display: table` approach in D8. But as @quicksketch reported a few weeks ago, that solution sadly doesn't work in all browsers, it turns out: https://www.drupal.org/node/2568597.

(Thanks for reporting, @quicksketch!)

If memory serves, before that, Drupal (contrib) used to use an approach where the HTML contained the width of the image, and the CSS relied on that width. This was supposed to be the pure CSS solution.

It's hard to believe nobody has solved this. Then again, most sites don't use generic solutions, but rely on stricter constraints.

Really curious what the solution is going to end up being.

---

Al that being said, I can't actually reproduce this.

This is @wesruv's codepen, updated to use Drupal 8's `display: table`-based CSS: http://codepen.io/anon/pen/RWgoXd. It seems to work fine, both in Chrome and Firefox.

What am I missing?

**Comment by wesruv** [comment]
@wimleers the responsiveness is the issue :disappointed: 
![image](https://cloud.githubusercontent.com/assets/5607236/10434103/74d253fa-70e5-11e5-8e51-82a84e4577ea.png)
This is the latest Chrome on Windows on your Codepen.

**Comment by tarekdj** [comment]
@quicksketch a quick fix : 
https://www.drupal.org/node/2568597#comment-10443957

**Comment by wimleers** [comment]
@wesruv Ah, thanks, that's crystal clear. Not sure how I missed that!

**Comment by wimleers** [comment]
@wesruv Hrm, the solution actually is rather simple: http://codepen.io/anon/pen/pjrYaN — just add `height: auto`. What's missing now?

**Comment by wesruv** [comment]
IE11: :disappointed: 

![image](https://cloud.githubusercontent.com/assets/5607236/10489856/ae6b98d2-726c-11e5-9fd2-8584de6a47f5.png)

**Comment by tarekdj** [comment]
@wesruv I think Firefox has the same issue. You can have a look at the patch I've sent here https://www.drupal.org/node/2568597#comment-10443957

**Comment by wimleers** [comment]
Gahhh! IE has come back to haunt us once more? :P

**Comment by wimleers** [comment]
I wonder if we can use flexbox to solve this? 80% of the global audience supports it unprefixed according to http://caniuse.com/flexbox.

So then we can continue to rely on the existing CSS as a fallback, but solve it for modern browsers (i.e. the 80%).

**Comment by jenlampton** [comment]
Flexbox++

**Comment by quicksketch** [comment]
It looks like the original bug has been fixed in Firefox (though not in a current stable yet): https://bugzilla.mozilla.org/show_bug.cgi?id=975632

Firefox is currently version 45.0. It's fixed in 46.0 and 47.0.

**Comment by wesruv** [comment]
Oooh, I think you're right @wimleers

**Comment by wesruv** [comment]
Oops, misunderstood this apps interface. I'll give flexbox a shot later today.

**Comment by wimleers** [comment]
@quicksketch Oh, yay! Does that mean we should no longer even bother fixing this? Once Firefox 47 is spread widely, this won't be a problem anymore. Doesn't seem to be worth any more of our time then?

**Comment by wesruv** [comment]
FWIW: Flexbox doesn't seem to solve the issue either, if the container is wider than the image it stretches the image horizontally.

http://codepen.io/wesruv/full/pymdZe/

**Comment by klonos** [comment]
I confirm what @wesruv says on Firefox 49 x64 nightlies on Windows.

**Comment by wimleers** [comment]
Firefox 47 has been rolled out. Does that mean we can close this?

**Comment by wimleers** [comment]
Bump.

**Comment by wimleers** [comment]
@quicksketch, @wesruv: thoughts?

**Comment by quicksketch** [comment]
So finally coming back to this, it does appear that the problem with the `display: table-caption` approach has finally disappeared. As such, I think we should revert back to the original approach.

I don't think Drupal needs to do anything at all because it never changed from the table-CSS approach in the first place.

I'll roll a PR for Backdrop.

**Comment by jenlampton** [comment]
Removing `audience - design` because we don't need mockups or design review on this one. Adding a milestone since this is a bug, and we have a PR that fixes this, and it simply needs a review. @quicksketch it's been a while since you filed that PR, do you want to do a rebase real quick?

**Comment by quicksketch** [comment]
New PR pushed up at https://github.com/backdrop/backdrop/pull/1959.

This got a little more elaborate because we need to provide Basis-specific styles. I made a new component file for "caption.css" and moved the styling for captions in there. Now Basis and Bartik both have proper wrapping of captions on images.

*Basis Edit:* (from components/caption.css)
![image](https://user-images.githubusercontent.com/100206/29478199-9777429e-8420-11e7-9ee4-7aa2dc4cc526.png)

*Basis View:* (from components/caption.css)
![image](https://user-images.githubusercontent.com/100206/29478203-9ef2a84c-8420-11e7-8283-f9001aa3d3c0.png)

*Bartik Edit:* (inherited from ckeditor-caption.css)
![image](https://user-images.githubusercontent.com/100206/29478238-cc7801f4-8420-11e7-9c65-b58a1e1b0819.png)

*Bartik View:* (inherited from system.theme.css)
![image](https://user-images.githubusercontent.com/100206/29478216-acfab38a-8420-11e7-9bf3-b427bbf34c46.png)

**Comment by quicksketch** [comment]
Merged https://github.com/backdrop/backdrop/pull/1959 into 1.x and 1.7.x.

Note that caption styles do not match when Basis is the default theme in CKEditor in 1.7.x because we only started adding theme-level CSS files to CKEditor in #1198, which is only in 1.x.
