### ISSUE TITLE
Layout UI: Moving a block around should trigger the "dirty" form flag.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#1622]
While trying to help @bd0db in #1574, I've noticed that if I move blocks around either within the same region in order to reorder them or to a different region, the "This form has unsaved changes." warning is not shown. Shouldn't it?

**Comment by klonos** [comment]
...same when you remove a block.

**Comment by docwilmot** [comment]
Done.

**Comment by quicksketch** [comment]
Could we use the same message both when a block is removed and when moving blocks around? The message for "Block X removed." doesn't tell me anything new. Seems like the same message should be displayed both when moving or removing (`This form has unsaved changes. Click "Save layout" to make changes permanent or "Cancel" to discard changes.`)

**Comment by docwilmot** [comment]
I thought this, but that was the message already there if `!backdrop_is_ajax()`. But agreed, changed, pushed.

**Comment by quicksketch** [comment]
Looks like there is still an issue as noted by @klonos in the PR:

**Comment by klonos** [comment]
FYI, I've also filed #1722 which is closely related.

**Comment by klonos** [comment]
I think we should keep these as separate cases. Let's deal with removing blocks in the other issue because it seems that this action does trigger the "dirty" flag - it is simply the message that is not displayed (it is shown on page refresh). Whereas with moving regions around, there is no "dirty" flag set at all. Refreshing the page returns the blocks to their original places.

**Comment by docwilmot** [comment]
Somehow the PR for this is closed, dont know why.
