### ISSUE TITLE
[UX] Project Browser: Searching for projects does not work properly or at all.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#2014]
Searching for "webform" returns 2 results:

- Webform
- Webform Remote Post

[Checking this search term with in the list of Backdrop CMS contributed projects](https://github.com/backdrop-contrib?utf8=%E2%9C%93&query=webform) shows the same two results. That's working as expected.

Searching for "printmpdf" though brings 0 results. That's an example. Most searches either return no results or an incomplete list 😞 

[Using the same term in the contrib projects list](https://github.com/backdrop-contrib?utf8=%E2%9C%93&query=printmpdf) brings the [printmpdf project](https://github.com/backdrop-contrib/printmpdf) as a result. So does [searching for "print"](https://github.com/backdrop-contrib?utf8=%E2%9C%93&query=print) or [for "pdf"](https://github.com/backdrop-contrib?utf8=%E2%9C%93&query=pdf).

Can we fix the Project Browser to at least return the result when searching with the project name and ideally make it work like the GitHub search in the contrib projects (partial search and AJAXy as-you-type)?

Also, this is a pretty major UX- in one of our best-selling features, so can we please try to address it in the next release?

**Comment by serundeputy** [comment]
This is most likely the same problem as https://github.com/backdrop-ops/backdropcms.org/issues/264 where the packages are not created properly do to API change on github side.

So,  once #264 in ops is resolved this should be too; correct me if I'm wrong @Gormartsen or @quicksketch 

thanks,
~Geoff

**Comment by klonos** [comment]
I filed that issue too 😄 

...indeed, the respective project nodes for the projects that are not working in Project Browser seem to not have been created in backdropcms.org. If that is the cause of this (most likely), then these issues will go away once https://github.com/backdrop-ops/backdropcms.org/issues/264 is resolved. If that happens, then I'll re-purpose this issue to a feature request to have search-as-you-type implemented.

There's also the issue about the search not returning results in the proper order: https://github.com/backdrop-ops/backdropcms.org/issues/232

**Comment by quicksketch** [comment]
The packaging issue at https://github.com/backdrop-ops/backdropcms.org/issues/264 has been fixed, so that shouldn't be an issue any more.

I found that searching for "printmpdf" on BackdropCMS.org itself yielded the right hits:
https://backdropcms.org/modules?s=printmpdf&url=

But that searching in the Project Browser still isn't quite what it should be. You can search for "print" and find "Print using mPDF", but the machine name doesn't turn up anything.

It does seem like this is a backdropcms.org issue rather than a Project Browser one. PB is just showing what backdropcms.org is returning for the given query. So we'll probably need to fix this in backdropcms.org's code, specifically in `borg_pbs_project_browser_server_query()`, which is responsible for doing such searches.

**Comment by quicksketch** [comment]
I took a look at this but I couldn't figure out why uploads aren't working on my first pass. It looks like the archives are being uploaded properly and everything, because if you upload an invalid archive it still unzips it and throws a validation error. The problem just seems to be in the redirection code. Project Browser isn't returning an AJAX command to redirect the page. The AJAX request itself is getting redirected via a `302` redirect, which just results in a JS error because the page doesn't get back the expected JSON response.

**Comment by quicksketch** [comment]
Oh, I'm getting issues mixed up. The actual search problem has been fixed, not in Backdrop but on BackdropCMS.org: https://github.com/backdrop-ops/backdropcms.org/issues/282

This issue is fixed as a side-effect. 

> I took a look at this but I couldn't figure out why uploads aren't working on my first pass.

That is not related to this issue. We have a separate issue, but I can't locate it at the moment. :(
