### ISSUE TITLE
[UX][D8] Create/select layout for specific content type from the content type add/edit area.

### ISSUE THREAD

**Issue by bobchristenson** [backdrop/backdrop-issues#2894]
CURRENT PR TO TEST: https://github.com/backdrop/backdrop/pull/4685

This is the "sibling" issue of #1131 and part of the #345 meta-issue. Also part of #378. See https://github.com/backdrop/backdrop-issues/issues/2894#issuecomment-435840573 for details/screenshots.

The [Field Layout](https://www.drupal.org/documentation/modules/field_layout) experimental module in D8 core seems to be doing this:

> One of the nice improvements that went in Drupal 8.3 was the Field Layout module, which provides the ability to apply pre-defined layouts to what we call "entity displays". Instead of applying layouts to individual pages, you can apply layouts to types of content regardless of what page they are displayed on. For example, you can create a content type 'Recipe' and visually lay out the different fields that make up a recipe. Because the layout is associated with the recipe rather than with a specific page, recipes will be laid out consistently across your website regardless of what page they are shown on.

https://www.youtube.com/watch?v=mJBHQJFHqws
https://www.youtube.com/watch?v=YC3zDt_cR2g

---
Newer issue by @stpaultim 

## Description of the need

Field blocks are one of the most powerful and useful features that are very hard to find or discover in Backdrop CMS. Over the years I have enjoyed watching the expressions of joy on the face of site architect's as I show them this feature, while growing increasingly frustrated that almost no one (including myself) finds it on their own or through documentation. 

In modern Drupal, with the new layout buider installed a site architect is able to enable layouts, click manage layout for that content type and they are presented with a customizable layout that already has visible field blocks for all of their fields. It's quite easy to discover and use this ability to drag and drop fields from one region to another within the core UI.

I think that we can simulate this experience in Backrop CMS and make field blocks a much easier feature to find and use.

## Proposed solution

I haven't decided on what I think is the best workflow for this yet. But, I'll share this idea to get the discussion going and I welcome ideas for how to improve on this. 

1) Add a "Create Custom Layout" option to the drop down for each content type on the Content Type page. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/fd606d8a-8009-4bf2-80ec-e465f958a5c8)

Clicking on this link, would take person to a preconfigured layout that looks something like this:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/fbbd66b3-f73c-450e-ba25-51c2cf60e36b)

This would already be completed and saved but could be edited:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/a4f7bab4-55d0-41a2-b20c-75d78e754c53)

## Alternatives that have been considered

I have not yet considered many alternatives. I am sure there are more complicated and far reaching solutions to this problem, but I see this solution as a step in that direction. Since this PR does not really add or change any functionality in Backdrop CMS, it just brings an important feature closer to the surface where folks will be much more likely to find and use it on their own.

Is there a Drupal or Backdrop contributed module that accomplishes this?

The Layout System is quite different in modern Drupal, but there is a workflow very similar to this built into Layout Builder.

## Additional information

In Modern Drupal, one would accomplish the same thing on the Manage Display page for a content type:
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/962dfdb2-4df6-4da9-a236-68460f293281)

Clicking on the Manage Layout option in DRUPAL takes one to this page with field blocks that one can easily reorder or drag and drop into other sections/regions.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/677928f7-9ceb-43d7-ba2e-37e595a88e12)

## Concerns

I'd want to make sure that we're not confusing this feature with existing features to manage the display of content types.

## Draft of feature description for Press Release (1 paragraph at most)

Backdrop CMS now includes an easy to use wizard that makes it much easier to use the existing layout system to create custom layouts for content types and along the way helps new site architects find hidden features and better understand the layout system.

---
## Original issue summary by @bobchristenson 

As I started using Backdrop and learned about Layouts, I expected to be able to choose a default layout per content type in the UI.  So, for example, I expected to be able to edit my content type (ie. /admin/structure/types/manage/page) and in the 'vertical tabs' see a "Layout" tab.

In that tab I'd envision a simple selector that would default to the 'default' layout template, but listed all available/active Layout templates.  You'd choose one and that would be used in the backend for the content type.

I don't know a lot about Layouts, but it seems that technically making a selection here would enter a layout based on path (node/%) and would add a visibility condition for that content type....more or less making it a more streamlined (and obvious) process for per-content-type-layouts.

You'd then be able to manage/delete/whatever this layout in the Layouts screen (if you deleted the Layout or removed the condition/path, it would default the content type selection back to Default)

Just a perspective from a D7 user coming to Backdrop...hope the idea is helpful!

ADVOCATE: @stpaultim

**Comment by Graham-72** [comment]
At the moment you can set up one layout per content type, so if you want to use two or more page layout options in a site you need to define separate content types for each. You can then choose which layout will be applied by choosing the content type when creating the node e.g. content types might be 'Page type A', 'Page type B' etc. But what you cannot do AFAIK is edit a node from being one content type to another. 

I am trying to think of an example where one might want to do this. Perhaps one layout might be single column, another two column? Is this what you have in mind?

One can do quite a bit with blocks, either custom blocks or ones produced by views, placing these in different regions of the layout. But in all cases one has to consider that screen width is going to impact on layout in a responsive site and it is often difficult for the site designer or editor to be in full control.

I have dreamt of a home page being a grid of regions, with the ability to drag and drop blocks into the different regions, together with the ability to specify the arrangement of blocks for each of the layout width break points. All under the day-by-day control of a site editor! Just like laying out a magazine page but with versions for widescreen, tablet and mobile phone.

**Comment by bobchristenson** [comment]
What you suggest (different layouts per node) would be ideal, but that's not what I'm suggesting here.  What I'm suggesting is much simpler...just a UI tweak.

I'd expect that lots of people would like to define which layout template to use for which node type (not individual nodes).  So all I'm suggesting is a UI component in the content type configuration screen that allows you to choose (via a dropdown) which layout template that node type uses.

This is just a friendlier way than figuring out that you have to go into layouts, create a new node/% layout, set conditions for content type, etc.

My suggestion is more of a UX addition that I think most people would want rather than a whole new functionality.

**Comment by jlfranklin** [comment]
Per-node layouts would make a great contrib module.

**Comment by olafgrabienski** [comment]
@bobchristenson - I like your suggestion to make Layouts visible in the content type configuration because the Layouts UI is not very intuitive in making clear how to create a Layout for a content type. For experts, it would however be a nice configuration shortcut!

So the request indeed isn't about a new functionality but about better user experience. As such, it reminds me the [Better node-type permissions](https://github.com/backdrop/backdrop-issues/issues/900) introduced in Backdrop 1.3.0.

@jlfranklin For the reason mentioned above I don't agree with the issue status "contrib candidate". What do you think about it?

**Comment by klonos** [comment]
This feature is available in D8.6 core via the (experimental at the moment) Layout Builder module. Once the module is enabled, a "Use Layout Builder" option becomes available in the "Manage display" tab of content types:

![screencapture-8-6-2-local-admin-structure-types-manage-article-display-2018-11-05-21_33_41](https://user-images.githubusercontent.com/2423362/47993237-19fefd80-e143-11e8-9b57-6b0a436094f5.png)

...once this option is enabled, the standard list of fields in that tab is replaced by a "Manage layout" button:

<img width="704" alt="screen shot 2018-11-05 at 9 35 44 pm" src="https://user-images.githubusercontent.com/2423362/47993386-6fd3a580-e143-11e8-8789-e207a4541170.png">

...which then takes users to the actual Layout Builder:

![screencapture-8-6-2-local-admin-structure-types-manage-article-display-layout-default-2018-11-05-21_54_32](https://user-images.githubusercontent.com/2423362/47994104-75ca8600-e145-11e8-91ab-b575f7e6f014.png)

Notice that the D8 layout builder works differently than Backdrop in that it allows configuring only the layout of the main content area. To manage other areas of the page, one needs to use the traditional block administration page.

The D8 Layout Builder has a more frontend-like feel, and there is dummy/placeholder content in place of the fields already configured in the content type (image, body text, tags, links, comments). These are actually field-blocks that can be dragged from the main area into other "sections" that can be created.

Another thing that can be done is to allow per-content item layouts (#1131).

**Comment by adriannolt** [comment]
When asking on Gitter about applying layouts to non-full/default view modes, I was referred to this issue. Is this the place to discuss being able to use layouts on all view modes, is there another issue, or should I open one?

**Comment by olafgrabienski** [comment]
> Is this the place to discuss being able to use layouts on all view modes, is there another issue, or should I open one?

@adriannolt I've searched the queue and found issue #2608 with the following suggestion in https://github.com/backdrop/backdrop-issues/issues/2608#issuecomment-291273853:

> I think in future every view mode should be configured in Layout UI.

It follows an interesting discussion about the topic. I consider to read it and to decide then if you open a new issue (then it'd be helpful to copy some comments over) or to revive one of the existing issues.

**Comment by adriannolt** [comment]
@olafgrabienski Thank you for your pointers. I will comment on those issues over there. That said, I also love the idea of this issue, so that, from a content type's manage display area, I would be able to directly access and edit a layout for that page.

**Comment by stpaultim** [comment]
This is such a great idea, that I reinnvented it for (probably the 5th time) here: https://github.com/backdrop/backdrop-issues/issues/6434

I was not aware of this issue before or I would have posted my thoughts here. I'm inclined to keep the newer issue going, since it already has a PR and some momentum. But, I think it's a duplicate of this one. 

@bobchristenson Should we close this one in favor of the new issue or do you think this one is different? (@klonos ?)

**Comment by jenlampton** [comment]
> Should we close this one in favor of the new issue 

We usually close the newer issue in favor of the older one, I'm going to copy the comments from that issue over here.

**Comment by jenlampton** [comment]
Comment from @stpaultim 

I'm not sure how to create a PR to do this. But, I THINK that this should be a relatively easy PR to create for those with better programming skills than I have, because it seems like all it's doing is preconfiguring a layout using existing tools and configuration.

Any feedback on the difficulty level for this feature and or suggestions on how to get started with a PR? Maybe help with some pseudo code?

**Comment by jenlampton** [comment]
From @stpaultim 

> Looking forward to testing it.

**Comment by jenlampton** [comment]
From @docwilmot 

POC PR up now.

- Adds a "Manage layouts" tab to all entity bundle configuration pages (page nodes: admin/structure/types/manage/page/layouts, user: admin/config/people/manage/layouts, taxonomy)
- That page shows all layouts overriding that entity type's display (eg node/%, user/%, taxonomy/term/%), and any layouts overriding the bundle type e.g layout with a page content type visibility condition.
- Allows adding a new layout with visibility conditions set automatically
- New layouts have all that bundle's field block in the content region automatically

Not fully tested, YMMV!

**Comment by jenlampton** [comment]
From @stpaultim 
---
@docwilmot - It's very exciting to see progress on this. Not sure if your ready for feedback, but I'll give some easy and obvious feedback and ask a few questions.

1) Layout page for all content types is full of these errors.

```
Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in layout_context_required_by_path() (line 2131 of /var/lib/tugboat/core/modules/layout/layout.module).
Deprecated function: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in layout_context_required_by_path() (line 2138 of /var/lib/tugboat/core/modules/layout/layout.module).
```

2) All the field blocks are currently showing up in the footer. I think that they should be in whatever region the "content" block was. 

3) Currently, the content block remains on the new layout. I would assume we should remove this block, since the field blocks would replace it. I don't think we need the "content" block on these new layouts.

4) In your PR, each entity type or content type has it's own layout page that shows layouts for that content type. I had not imagined this. I guess, I don't expect that content types are likely to have more than one layout and it seems excessive to have an entire page to list one layout. Is this an interim step in developing this feature or are you imagining that this layout page for each content type is useful?

5) I like that you are thinking about other entity types than content types. I had not thought that far out yet. But, I can see how this same feature could be very useful for vocabularies/taxonomies. Good work on this.

6) Just a note: I tested creating a layout through the content type interface and it showed up in the layout interface as expected. I also tested creating a layout through the layout interface that had a visibly rule specific to one content type and it showed up in the Content Type interface as expected.

I think, I'll leave my comments here for now, since I assume this PR is still in progress and may still be changing. 

But, I love where this is going!

**Comment by jenlampton** [comment]
From @hosef 

I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

**Comment by jenlampton** [comment]
From @stpaultim 

@hosef - For me, the most important part of this is to provide easy access to field blocks. If they are not all visible, then how do you decide which ones to make visible? And if the content block is visible, then some data is duplicated, unless you also change the display settings.

Any specific proposals for how you think this could work better?

**Comment by jenlampton** [comment]
From @herbdool 

Looks like an awesome feature.

Maybe there's a way to provide an option of using the default content block or add field blocks. The wizard is useful for both approaches (those who just want an easy way to configure the context and visibility; and those who want a more complex layout) so it would be good to figure this out.

**Comment by jenlampton** [comment]
From @docwilmot 
---
>Layout page for all content types is full of these errors.

Should be fixed
> All the field blocks are currently showing up in the footer. 

Fixed
> Currently, the content block remains on the new layout. I would assume we should remove this block. 

Done. Wasn't sure this would be preferred, please see @hosef's comment.
> In your PR, each entity type or content type has it's own layout page that shows layouts for that content type. I had not imagined this. I guess, I don't expect that content types are likely to have more than one layout and it seems excessive to have an entire page to list one layout. Is this an interim step in developing this feature or are you imagining that this layout page for each content type is useful?

This seemed the more logical way to do it for me. I suppose a single layout page per entity instead of per bundle may make more sense though, so I'm open to other ideas.
> I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

This is reasonable, but then if we're hoping this feature will make field blocks more visible, how could we do that? Pick a random field block and enable it in a random region? Open to suggestions

**Comment by jenlampton** [comment]
From @stpaultim 
---

>Layout page for all content types is full of these errors.

Should be fixed
> All the field blocks are currently showing up in the footer. 

Fixed
> Currently, the content block remains on the new layout. I would assume we should remove this block. 

Done. Wasn't sure this would be preferred, please see @hosef's comment.
> In your PR, each entity type or content type has it's own layout page that shows layouts for that content type. I had not imagined this. I guess, I don't expect that content types are likely to have more than one layout and it seems excessive to have an entire page to list one layout. Is this an interim step in developing this feature or are you imagining that this layout page for each content type is useful?

This seemed the more logical way to do it for me. I suppose a single layout page per entity instead of per bundle may make more sense though, so I'm open to other ideas.
> I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

This is reasonable, but then if we're hoping this feature will make field blocks more visible, how could we do that? Pick a random field block and enable it in a random region? Open to suggestions

**Comment by jenlampton** [comment]
from @docwilmot 
---
I think the normal layout block add page should be the definitive place to do layout stuff. I think we should consider this PR to just be making a shortcut to lead to that location. I think some good help text on the entity layout page, and a message after layout creation explaining what happened, maybe even a link back to the entity layout page?

Not sure. Usually this is when @jenlampton and @klonos come in right?

**Comment by jenlampton** [comment]
From @hosef 

> I think that if they start in the content types section, they should end up back there after going through the wizard. I can see new users getting confused by ending up somewhere else when setting up a new content type.

**Comment by jenlampton** [comment]
from @klonos 
---

Thanks @stpaultim for bringing this issue here to my attention. I have not read the whole thread yet, but it seems to be a duplicate of #2894 ...right?

**Comment by jenlampton** [comment]
from @jenlampton
---

Wow, thanks for the quick PR @docwilmot ! 

> Adds a "Manage layouts" tab to all entity bundle configuration pages

Instead of "Add layout: I'd like to see two different action links on this new page.  Recommendations for link text the weekly meeting were: `Create a layout for all content` and `Create a layout for [Page] content`.  

`Create a layout for all content` will create a layout for `node%` with no visibility rules, and `Create a layout for [Page] content` will create a layout for `node%`, and also add the visibility condition for node type = . Page.  

(What we talked about in the meting was... ) In both cases the result of clicking the action link should land someone on the "Mange blocks" interface, skipping the "Add new layout" form entirely, but assuming sensible defaults (like copying the default layout + layout template).

The layout _state_ should be saved at this point (but it should not yet be stored in configuration) - so people can get to the "manage blocks" to see what it does, but a "cancel" here would not result in a layout existing. 

> This is what a content type layout page looks like after a layout has been created.

If a layout already exists for `node/%`, that one should appear in the list of layouts also. Maybe we can separate it the same way we do "Default layouts" on the manage layouts page?

> I like the idea, but I am not sure about having all the field blocks in there by default. Usually I just want the default content block and then 1-3 fields moved to other regions.

I agree with @hosef, I think the opposite is far preferable. The most common use-case is that people will only have one or two field blocks, and all other fields are shown via by the display mode. Placing all the field blocks will create a lot of work for people to remove them.

> I don't think we need the "content" block on these new layouts.

~People probably will not understand they need that "existing content" block in order to get the page to work properly.  (Isn't there even a warning showing on the page when it's missing?)~ Was this fixed? 

> I think the normal layout block add page should be the definitive place to do layout stuff. 

I agree with this -- all the new stuff should just be taking people to & from the current manage layouts interfaces.

> I think that if they start in the content types section, they should end up back there after going through the wizard. I can see new users getting confused by ending up somewhere else when setting up a new content type.

I agree, but it can probably be done using a `destination` parameter (we don't need a separate interface).

**Comment by jenlampton** [comment]
from @docwilmot 
---

> (What we talked about in the meting was... ) In both cases the result of clicking the action link should land someone on the "Mange blocks" interface, skipping the "Add new layout" form entirely, but assuming sensible defaults (like copying the default layout + layout template).

I considered this but I dont think it is the most logical way to approach it. The user would end up with a layout with the wrong template each time (if the default template really was already sensible, the user wouldnt need a different layout for node pages), and have to go through several clicks to re-configure and save a new template each time, instead of selecting their preferred template up front.

**Comment by jenlampton** [comment]
from @docwilmot 
---

>  this PR adds layout pages for all entities

I saw this in the demo, but forgot to mention it: these aren't `Layout pages`, these are all `Layout overrides` since they use an existing path, we should be careful not to confuse people by using the wrong terminology :)

**Comment by docwilmot** [comment]
> these are all Layout overrides since they use an existing path, we should be careful not to confuse people by using the wrong terminology :)

To clarify, when I say "layout pages" I'm referring to the `admin/structure/types/manage/card/layouts` or `admin/structure/taxonomy/tags/layouts` page, not the `node/%` page.

**Comment by stpaultim** [comment]
Just reading through the recent comments to see what decisions still need to be made. I think that if @docwilmot has a little time and motivation, this issue could be a candidate for 1.28 release. 

- [ ] On the layout page for each entity type, have two links `Create a layout for all content` and `Create a layout for [Page] content` [More info](https://github.com/backdrop/backdrop-issues/issues/2894#issuecomment-2040255303)

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/6b3c8dbe-4bf8-4e1c-98a2-ea263f4230c7)

- [ ] Decide on whether or not clicking on create new layout links takes people directly to "manage blocks" page? [More info](https://github.com/backdrop/backdrop-issues/issues/2894#issuecomment-2040255303)

- [ ] Resolve potential UX issue dealing with switch between `admin/structure/types/manage/page/layouts` and `/admin/structure/layouts/manage/page_layout`. This seems like it might confuse site architects that are configuring a content type and then find themselves in the layout configuration with no direct link back to where they were.

- [ ] RELATED to previous point - if one is on the list of layouts for a content type and delete a layout. One does not come back to this page as expected, rather one is taken to `admin/structure/layouts`, which is a bit confusing.

- [ ] Fix these words. `No layout pages have been created yet.` [More info](https://github.com/backdrop/backdrop-issues/issues/2894#issuecomment-2040259054)

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/4fdadac5-2dfe-48d4-9d50-aed95d80f99a)

**Comment by stpaultim** [comment]
In the last comment, I listed the outstanding issues from recent comments. Here are my thoughts on some of them. 

1 - I don't object to this idea. But, I fear that it complicates the PR a bit and might slow us down with what could be seen as a slight different issue, creating a layout for all content. Until now, this issue is focused on adding a layout for specific entity types.  I do think the suggestion is good and would be happy to see this in this PR, but I can also envision this as a follow-up issue.

2 - After clicking create layout link, should person select layout template and whether to use "content" block or "field blocks" OR  go directly to block management page. At this stage, I'm inclined to keep the process as it is, because I REALLY want to see the option to replace the "main content" block with field blocks. This is, in my opinion, the most powerful aspect of this feature. 

If there is an option to `Create a layout for [Entity] content with field blocks` - then I can see why we might skip this following page. But, since not everyone would like to replace the "main content" blocks, I think it's important that we give the person this choice somewhere before they get to the manage blocks page.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/cfc5d11d-db58-4b95-b9af-c65651bf2574)

3 & 4 - I think this is a real problem, but I'm not sure of the best solution. Could there be a link here back to the page to manage all layouts assigned to "Posts"?

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/13298a74-9ac8-468a-87d5-37d60d0fb90b)

5 - How about these words? `No layout overrides have been created for this entity type yet."

Atten: @docwilmot and @jenlampton

**Comment by docwilmot** [comment]
@stpaultim I've fixed most of the issues, except number 2 which I still believe is not the best UX.

**Comment by docwilmot** [comment]
Once there is some settlement is our discussion, I'll do some tests.

**Comment by herbdool** [comment]
Some bugs: 

No taxonomy name in link, plus some errors:

> Warning: Undefined array key "plural label" in layout_entity_menu_title() (line 645 of /var/lib/tugboat/core/modules/layout/layout.module).
> Warning: Undefined array key "all" in layout_entity_admin_form() (line 39 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
>Warning: foreach() argument must be of type array|object, null given in layout_entity_admin_form() (line 39 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).

On a content type config page: 

> Warning: Undefined array key "plural label" in layout_entity_menu_title() (line 645 of /var/lib/tugboat/core/modules/layout/layout.module). 

It's a bit weird to have a Create Layout for all content types on individual bundles. Maybe move it up a level. And that link doesn't appear for other entity types. Plus what should happen when choosing the field block option? Should it include all fields in all content types? At any rate, it doesn't do that. It seems to only insert the bundle last visited.

**Comment by stpaultim** [comment]
Here is the main entity layout page now:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/907da204-e2ce-46d6-800d-c4fa4b85f910)

@jenlampton I think we need your feedback on this to make sure we're understanding what you were looking for here. This matches my understanding of your suggestion, but I may have misunderstood.

Thanks @docwilmot !!! I really appreciate the work on this issue.

**Comment by stpaultim** [comment]
I'm advocating for this issue and have added it to the 1.28 milestone.
https://docs.backdropcms.org/documentation/adding-labels-to-issues

**Comment by herbdool** [comment]
> main entity layout page

I think you mean the layout page for the entity type "node" which has a bundle, "event"? It doesn't appear the same on the bundles of other entity types, such as the "tags" taxonomy.

**Comment by herbdool** [comment]
Another bug. If creating a layout for a user account, it's also missing the bundle name in the link. And if I choose field blocks, then nothing appears in the content region if there are no fields on the bundle. There should be a fallback to using the main content block.

**Comment by jenlampton** [comment]
> Thanks @docwilmot !!! I really appreciate the work on this issue.

💯 yes! same 😃 

> @jenlampton I think we need your feedback on this to make sure we're understanding what you were looking for here. This matches my understanding of your suggestion, but I may have misunderstood.

Yes, that's almost exactly what I envisioned!

I'd like it to flow in the same order as the manage layouts page, so the most specific at top to least at the bottom. (The layout listing page already uses a weight for this, we just need to use the same value here.)

If `node/%` has no layouts at all, we'd see only the site default layout template, if there was one for all node types, that would be above that, and one for this type would be above that. (This order is managed manually on the layouts page, maybe we should have the same "re-order" feature here?!)

hmm... this means well need to worry about setting this weight too when we create a layout, or at least warning people when it needs to be adjusted?

> Assuming that we keep this page working the way it is, we may need a label that says something to the effect of:  "All layouts effecting the [Event] content type:"

Yes, this heading would be great :) 

> if I choose field blocks, then nothing appears in the content region if there are no fields on the bundle. There should be a fallback to using the main content block.

That's an interesting use-case. I think I'd prefer validation failure if there were no fields on the entity, rather than creating something I didn't ask for? We'd need a warning stating that the block was still added, and why.

**Comment by docwilmot** [comment]
> I'd like it to flow in the same order as the manage layouts page, so the most specific at top to least at the bottom

Layout weights are set in `layout_load_all()` which we use to load each entity page so they'll be in order. A re-order page for this might be a bit much?
> Yes, this heading would be great :)

Where exactly?
> if I choose field blocks, then nothing appears in the content region if there are no fields on the bundle

Fixed. If there are no field blocks, you dont get the option to use field blocks.

**Comment by stpaultim** [comment]
This issue was discussed extensively in the Design/UX meeting today. 
https://www.youtube.com/live/F2jSqrlo7sU?si=tWh_7RikjdfQO2Dg&t=26m02s (link to exact spot in YouTube video)

@jenlampton raised a couple of concerns about the current approach. Here is my summary of how I understood her objections: 

1. The first objection is that when someone using the current process goes through the first step of process and clicks on the “create layout” button, the layout is created before they have had a chance to see the actual layout with blocks and it’s alreaqdy too late to back-out or cancel the process. Now the layout exists and if they don’t need it, it may just sit around unused unless they go back and deliberately delete it. 

2. The second objection is that giving someone the choice between the “content” block or replacing the “content” block with all the field blocks, is sub-optimal. According to @jenlampton, most people are not going to want to use field blocks for all fields, so providing them this option would require that they add the "content" region back and delete the field blocks they would prefer to leave in the content region. This option also has the potential to create confusion between the manage displays tabs and the manage layouts. 

Recommended solutions:

(still editing this comment)

**Comment by stpaultim** [comment]
@docwilmot and I just huddled in a Jitsi room to talk about this issue and make a plan forward. He is hoping to work on this issue more this weekend and then see how folks respond. 

Current Plan:

1. We both believe that it's important for people to choose their layout template for any entity type specific layout. We are not convinced that sufficient folks are going to be happy with the default layout template and that it does not make sense to take them immediately to a "Manage blocks" page that is not using the layout template of their choice.

2. When clicking on the create layout link (for all content types or a specific content type) you will be taken to page in the current PR, where you will choose A) which layout template you wish to use & B) which fields you would like blocks for. 

3. There will be a checkbox for "[ ] Custom block selection" (still working on the wording). I think that this will be "unchecked" by default, but I'm not certain.

4. If you check "[ ] Custom block selection." You will be given a list of potential field blocks along with the "Main Content" block. The "Main Content" block will be listed first and selected by default, the other blocks will NOT be selected by default. 

5. Once you create the layout, you will be provided with the "Main Content" block if you left the box checked and whichever field blocks you selected. 

6. We will work on help text to put in the appropriate places to help people avoid surprises and accidental breaking of their site. Specifically, we will inform people that they may want to disable fields in the Default Content Display to prevent duplication of content if they created field blocks. 

NOTES:

1. We understand the concern over having to create a layout before you see the block placement and the interest in finding a way to make this temporary, untill you are sure you want to keep it. But, we think that the workflow in the current PR matches the default workflow in core for creating layouts and believe that is a seperate issue. If that is a problem, we should talk about a universal solution.

2. Current plans suggest that we will NOT remove new field blocks from the Default Content Display automatically. We would like to leave this for a follow-up issue. Partly, because we think that this is an existing problem and that there should be a setting on all field blocks that allows you to hide them from the Default Content Display of any specific content type they appear in. We welcome discussion on this point. I plan to open a seperate issue to address this point.

3. We discussed whether or not it is necessary to have a layout page for each individual entity type or if it would make sense to have a single page for all Content Types, one for all Taxonomy Types, and one for Users. I'm not sure if we made a decision yet. We welcome your thoughts on this issue.

We hope that this moves the issue forward and welcome discussion and feedback on all points. 

@docwilmot Did I get this correct and/or did I forget anything important.

**Comment by docwilmot** [comment]
> @docwilmot Did I get this correct and/or did I forget anything important.

Sounds about right. I'd like to stress again that taking a user to a page to save a layout without choosing a template is not reasonable. The whole point of Layouts is to assign a template to a page. You'd end up on a page with a template you did not choose, and find there is no point moving blocks around because eventually selecting your preferred template will re-shuffle them again as regions change. 

I've pushed a new commit to allow selecting the field blocks you want to show (point 2, under current plan, above).

**Comment by herbdool** [comment]
I think that's an improvement for sure. I like the option to select which fields.

I think the Main Content option needs a bit more explanation next to it. Saying that it contains all the fields that are in the field display (with a link). And put help there that they can hide the field on that display so as to avoid duplicates.

I still don't like the "Create layout for all content types". Or at least the prominence it gets. Why is it on every bundle? There's already a default node layout so why do we need reminding on each bundle that we can create more? And people probably don't realize that there will be a clash of routes unless they start adding more visibility conditions. How about we move that to admin/structure/types where it makes more sense, or even just leave it to people to clone the default node layout, and don't have this link at all.

**Comment by herbdool** [comment]
Creating a layout for a vocabulary now looks like this: 

![Screenshot_20240420-175908](https://github.com/backdrop/backdrop-issues/assets/1071483/f2629fd3-3754-40bf-9ab9-4c4cc8f1d6ef)

They shouldn't be allowed to unselect the Main Content if there are no fields. Plus there are non-field things that vocabularies and users have that only appear in that block.

**Comment by herbdool** [comment]
Oops, maybe there isn't a node specific layout by default. Still my point stands that the link is too prominent. Put the link on the main content type page. And maybe just add a disabled default node layout.

**Comment by stpaultim** [comment]
@herbdool - You are correct, we definitely need better help text on this PR. I'll try to look closer and make specific recommendations later today. For now, here is a screenshot of a content type with more fields. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/a7b1cafa-ed2b-4288-b79c-8889eab43db1)

In discussion with @docwilmot and @klonos - I think we decided to change the boolean field for "Use field blocks" to radio buttons with options such as:

[ x ] Use "Main page content" block only
[    ] Add field blocks

Then only show the list of blocks when "Add field blocks" is checked. 

For for the Main Page Content block:

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/67828351-8b41-48f5-9e79-853e69cd4731)

Maybe add `"Main page content" block - default display for appropriate entity type.`

**Comment by klonos** [comment]
Counter-suggestion for the text for the radio options:
- (x) Keep all field blocks bundled within a single "Main content" block
- ( ) Select field blocks to be placed and managed individually

>  I think we should add some text somewhere that says something to this effect - "Adding field blocks may result in duplication of content unless matching field is hidden on the default display for the entity type."

I've created #6462 for that 😉 

Further feedback coming up...

**Comment by klonos** [comment]
OK, it took me a while to catch up on the comments in this thread, but finally done that. I also had a call with @stpaultim and @docwilmot earlier today, which helped with the catching up. Here's my feedback/thoughts after careful consideration (and admitting that I was ambivalent for certain things from time to time as I was reading through):

I see a lot of merit in what @jenlampton has proposed:
- When the "+ Add layout for XYZ content" or "+ Add layout for all content types" links are clicked:
  - The layout name is pre-selected, based on the name of the content type (or entity type or bundle).
  - The same layout template as the default layout is pre-selected (bare with me on that)
  - No option to split and auto-place blocks at this step (bare with me on that as well).
  - No need for a form to fill - we redirect users straight to a "Manage blocks" form -> UX+ and object achieved very quickly👍🏼 
- Once the layout has been created, and while in the "Manage blocks" form for that layout **_for the first time_**, we show these messages:
  > - Layout XYZ has been created successfully for [entity or bundle name].
  > - The XYZ layout template has been automatically pre-selected for this layout, because that's the template used in the Default layout. You can select a different layout template in the "Configure layout" tab.
- In every layout that allows field blocks to be placed, we add something like the following info message **_always_** (not just when the layout is created for the first time):
  > By default, this layout uses the "Main content" block to display the content of all available fields. However, separate field blocks can be placed individually by ... bla, bla, bla ...

The last bullet point above should help with the discoverability of the field blocks regardless, and we can consider that as part of #6462.

The above implies the following:
- We do not ship this feature here with any option to select and auto-place field blocks - this will be a follow-up feature.
- In the new follow-up feature, we add a new "Split field blocks" operation (name TBD) for the "Main content" block, and we make that operation the default (instead of the current default "Configure", which for this specific block offers very little value).
- When people click that operation, a step-by-step wizard guides them to select field blocks, and possibly (optionally?) the option to hide/exclude them from the main block in a single go.
- At the end of the wizard, we redirect back to the "Manage blocks" UI for that layout, with all selected "split" field blocks placed in the same region as where the "Main content" block was placed.
- We add a message saying:
  > The following field blocks have been placed in the XYZ region. You can move them to other regions if you like.
- If all available field blocks have been selected to be split out of the "Main content" block, we automatically remove that block and add a message to let people know that this has happened (or we don't, and we just show a message that says to consider doing that manually, because duplicated content etc. etc.)

So what I am effectively proposing here is to:
- reduce the scope of this feature here to only be auto-creating the layout (with sensible defaults + messages to explain that these defaults can be tweaked).
- create a follow-up feature request to create a wizard that allows "splitting" field blocks out of the "Main content" block (for layouts that apply to fieldable entities/bundles)

**Comment by herbdool** [comment]
So what @klonos is proposing, in my understanding, is splitting this issue up again. So that this is separate from @stpaultim's. This issue originally was a simple UI tweak to create a content type layout. And @stpaultim issue is about making it easy to place the field blocks.

**Comment by docwilmot** [comment]
> The same layout template as the default layout is pre-selected (bare with me on that)

I'm OK with the suggestions in @klonos post but not this one.  Again this makes no logical sense. We are prioritizing making things *look* easy for the *first-time* explorer at the expense of UX sanity for everyone else. A layout is to choose a template for your page. We're creating a situation where every experienced Backdrop user (and that includes our "first-time" user above once he's done this once) cannot easily create a new Layout for an entity. Youll need to click the create layout for Nodes button, then click the configure button, then select a template, then click save, then return to re-organize your field blocks. With the current UI, you select a template and create your layout, thats it. It would be wrong to complicate things this way for little gain. I'd be happy to continue but there's been no rational explanation above for why we'd do that, so I'm pausing here until reason appears.

**Comment by stpaultim** [comment]
After meetings with both @docwilmot and @klonos yesterday, it seem that our sticking point (and current blocker) with this issue is the following:

What should happen after clicking on this link. 

1. The person is taken directly to the manage block page, assuming that they are using whatever layout template is being used by default layout. 

or

2. The person is first taken to a page where they can choose which layout template they would like and taken to the manage block page after selecting a layout (and any other config options on that page). 

It might help to hear from some new voices. Which of these options would be the best user experience and why?

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/ade3c8b6-9851-4642-b8f1-354d56f7673e)

**Comment by yorkshire-pudding** [comment]
I think either of those would work and I don't think are overwhelming UX reasons for one approach over the other.

For 1, this may be the most common approach; use the default layout and just tweak blocks etc.

For 2, (I would add that the template used in the default layout should be selected by default), perhaps this way avoids the situation that you configure blocks, then decide you need a different template, and the regions are different so the blocks are placed elsewhere.  Also, perhaps from the "Manage blocks" page perhaps it is not obvious where you change the template; if this is your first foray into customising layouts then it may be more helpful to start on the Configure page so you can see the templates before you start customising blocks.

I'm fine with either approach, but think 2 may be slightly better for new users who are unfamiliar with layouts.

**Comment by olafgrabienski** [comment]
I also prefer no. 2, just gave it a try in the sandbox.

**Comment by jenlampton** [comment]
> We do not ship this feature here with any option to select and auto-place field blocks - this will be a follow-up feature.

@klonos  can we create the issue for this? There's a lot of discussion here that we should move over to that issue. 

> A layout is to choose a template for your page.

This not the majority use case. A layout is a set of rules place blocks on the page. Which template is selected is secondary, and most sites will only use 1-3 different templates, even they'll have lots and lots of layouts. The use-case we are solving for here doesn't include a different template, since that's not as common. 

> What should happen after clicking on this link Create a Layout for ______ content?

The most common use case is that people will either 1) want the default layout template, or 2) want the layout template that is in use on the "All content" Layout (if there is one). Very few people will want a different layout template. 

Understanding that the majority of people will not want to use a different template, we would actually making more work for the majority by adding this extra step in the middle. 

It's true that when you create a layout from the layouts listing page currently, you are asked for the layout template every time, so the pain-point we would be adding with the intermediary step is no different from the current pain-point we experience when adding layouts the old way.

It's also true that when adding layouts the old way many of us regularly forget to select a template on this step (causing an immediate validation error when we enter the path). The reason we forget to select a template so often is because which template is in use is not even something we're thinking about -- because it's not relevant to our current task: placing blocks on the page. 

I was hoping that we could remove that pain-point here (especially for new users!) since we have the opportunity to do so. 

That said, I don't want to hold up this issue. I just want everyone to acknowledge that we're going to make more work for most people most of the time by adding it. 

I do agree that it will make a better demo of "how to choose a different layout template" without it, and there is also value to having a nice demo.

**Comment by jenlampton** [comment]
> For 2, (I would add that the template used in the default layout should be selected by default),

I'd also like to see this default behavior for the "add layout" page from the layout listing page! Maybe I'll go make a separate issue for that now.  https://github.com/backdrop/backdrop-issues/issues/6479

**Comment by stpaultim** [comment]
> That said, I don't want to hold up this issue. I just want everyone to acknowledge that we're going to make more work for most people most of the time by adding it.

Since the existing method for creating layouts also requires this step, I would argue that at worst we're not creating more work but potentially missing an opportunity to create less work. :-) 

Even then, I'm not sure we have consenus on the point that the majoritty use case is to simply rearrange blocks and rules and not select a new template. But, I could be persuaded on this point, I don't think it's intuative. I'd love to know what the average number of layouts is on sites. I'm not sure if that is a practical thing to collect with telemetry or something we might at best gain anecdotal evidence on. 

I do believe that for more complex or ambitious sites, what you are saying has merit. But, I also build a fair number of simple sites with relatively few layouts (maybe 2-3 custom layouts). In these cases, it's often/usually the case that I am using a different layout template when creating a "node" layout.

Either way, I appreciate that we might call this a follow-up issue. @docwilmot has indicated that our current approach is technically easier, which is another reason to implement this now as a first step and to create a follow up issue. 

At the meeting on Thursday, we acknowledged the problem with layouts being created before people are necessarily committed to them and thought of a few ways to at LEAST make it easier to delete them if it turns out they are not needed. Including, simply adding a "Delete" button to layouts, simliar to what we provide on nodes. This might help with that situation. Should we include that in this PR or create a follow-up issue? Since this is really a valid idea regardless of this PR, I'm inclined to open an issue for just this request. 

(screenshot is from a node edit form)
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/e340b56a-7e37-49f1-a9a6-91bcf229c83e)

@docwilmot - I think this means we have consensus on moving forward with the PR using the intermediary step (at least for now). I know we have a few ideas about how to make this intermediary step a bit better.

**Comment by docwilmot** [comment]
I've done a new PR https://github.com/backdrop/backdrop/pull/4715 that adds the UI only to the Entity admin page level (ie not to all node types). So far only for Nodes. So far havent added the links to the content type configure dropbuttons, because I'd need to do it on the other PR as well if we preferred that one, and  dont want to duplicate.

Turns out this UI will be more complex because we'd need to offer a means to choose which bundles (node types), so theres a checkbox list for that. I've wrapped the extra form elements in fieldsets to make them less intrusive since there may be both long lists of content type as well as long lists of fields.

Feedback welcome of course.

**Comment by stpaultim** [comment]
I recommend testing this in the available PR sandbox. But, just in case, here are some sreenshots for the alternative PR. 

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/1120839e-3f03-4eed-b029-ead6a998b8e4)

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/9bc49e87-2b63-4bcb-b9c5-4caff099de5e)

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/377e1e87-4053-4430-9f92-a0e4962c4eb9)

I like this second approach, I think it's a bit simplier and easy to access, but I know that some folks have expressed a strong preference for keeping the layout tab for each entity type and I'm also good with that approach.

**Comment by stpaultim** [comment]
Once concern about the current implementation of the second approach is that it is possible to ask for a layout that for a content type (example `Post`) that includes a field block for `Sponsor`, even though Sponsor is only available to the `Event` content type. 

If I do this, I get a layout that will only apply to `Posts`, but has an unused `Sponsor` field block. While, this doesn't really hurt anything, it could be confusing to a site builder. 

In our original implementation, once could create a layout for a specific content type and would ONLY see the option to add fields available to that content type.

![image](https://github.com/backdrop/backdrop-issues/assets/3144571/fa6414a8-f9e6-41ed-8f04-1fc0b71bb154)

Possible fixes:

1) When listing field blocks, include a list of content types that use them. 
2) Require person to select content type first and then when selecting field blocks, only show them relevent field blocks.

**Comment by herbdool** [comment]
I like this approach better too. 

It also gets rid of that awkward two links for  "all" content types vs "[page]" content types. And I can see all the node-based layouts together.

**Comment by stpaultim** [comment]
For there to be any chance of getting this into the next release, we need to select which approach we favor quickly, so that we have time to polish the UI, labels, and help text.

**Comment by argiepiano** [comment]
I'm coming very late to this topic, but I just tried the new PR. 

I'm testing using a typical workflow for a site builder: creating a new content type, which takes me to `admin/structure/types/manage/a-new-type/fields`. At this point, as a site builder, I can add fields, manage displays etc, but I don't see "Manage layouts" tab at all there. To see that tab I need to go back to the list of all content types. I find this somewhat counter intuitive - after all, when I create a content type, I expect to have all the "tools" related to this content type in one place. The previous PR did have this, and therefore I prefer that one.

Anyway, if people feel this new PR is preferred, I'd suggest that the fieldset "Select Content type to use this layout" should be open, since it contains required checkboxes. And perhaps find a better wording for the fieldset.

**Comment by herbdool** [comment]
Good point @argiepiano. It's also good to have the tab there. 

I'm not optimistic this will get in. But that's good because we shouldn't rush this when there are major differences in opinion.

**Comment by docwilmot** [comment]
This does require more time for agreement than I think we have. I agree it would be rushing things to try and get it in.

**Comment by stpaultim** [comment]
I've suggested that we talk about this issue at the next Design/UX meeting on June 13th. I think we need an in person discussion to get this moving again. 

I believe that our largest blocker right now is coming to some consensus on whether or not to include the "Manage Layouts" tab for each specific entity/content type OR to have a single page for all content types. 

One page for all content types:
https://github.com/backdrop/backdrop/pull/4715
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/1ec7e18a-9a01-485d-b452-4c05a471da41)

Option for each entity type:
https://github.com/backdrop/backdrop/pull/4685
![image](https://github.com/backdrop/backdrop-issues/assets/3144571/ce37a9d7-f290-4972-920c-a77322ddfddc)

**Comment by stpaultim** [comment]
@docwilmot This was discussed during the Design/UX meeting today, if you want to watch the discussion. We talked about this for about 20 minutes, early in the meeting agenda.

**Comment by klonos** [comment]
> After a "Layout for [Post] content type" has been added, that one will appear above the other two on both pages.

May I add: but should not appear on the "Layouts" pages of other content types - only on the one for Post.

> This was discussed during the Design/UX meeting today ...

The discussion about this specific issue starts at 14:57 into the recording. Here: https://youtu.be/l2SAcL907AQ?t=897

**Comment by docwilmot** [comment]
Yet another PR for this, essentially merges the previous two. Layout tabs both at entity and at bundle level. 

Also, now, the layout does not save until you click "Save layout" on the add blocks page.

**Comment by stpaultim** [comment]
@docwilmot Sorry it's taken a while to review your PR. 

In general, I think this is looking good. .I am seeing a bug that you may or may not be aware of. 

If you go to `/admin/structure/types/layout` and click on `Create a layout for content types` - there are some warnings and bugs. 

![image](https://github.com/user-attachments/assets/4136edb9-4d87-4062-8c5a-56a1ceb5673a)

Going to individual content types and creating layouts seems to be working as expected!

**Comment by docwilmot** [comment]
Thanks @stpaultim. That error should be fixed now.

**Comment by klonos** [comment]
@docwilmot there's at least one stray `dpm()` that causes this error:
> Error: Call to undefined function dpm() in layout_entity_admin_add_form() (line 232 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).

**Comment by docwilmot** [comment]
Thx, fixed.

**Comment by stpaultim** [comment]
Little thing. Can we make sure that "Manage Layouts" always comes immediately after "List content types". 

It's a bit weird to have it in the middle of the actual content types.

![image](https://github.com/user-attachments/assets/d6b6e88d-15a0-4f60-abea-519d6baaaa9a)

@docwilmot

**Comment by stpaultim** [comment]
My expectation when I clicked on "Create a layout for content types" was that I would be given a choice of one or more content types to create a layout for. 

This form is seems to be limited to creating a layout for all content types. Maybe, we should just add the word "all" to the link/page title.

"Create a layout for all content types"

NOTE: My first reaction was to suggest some help text for this page to make it clear. But, on reflection it seems like just adding that one word might do the trick.

![image](https://github.com/user-attachments/assets/768f2bf0-891b-41ef-a9be-5d6c8065e98a)

**Comment by stpaultim** [comment]
After clicking on the "Create Layout" button to "Create a layout for all content types" I get these warnings.

```
Warning: Undefined array key "field_name" in layout_entity_admin_add_form_submit() (line 382 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
Warning: Undefined array key "" in layout_entity_admin_add_form_submit() (line 382 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
Warning: Undefined array key "field_name" in layout_entity_admin_add_form_submit() (line 382 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
Warning: Undefined array key "" in layout_entity_admin_add_form_submit() (line 382 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
Warning: Undefined array key "field_name" in layout_entity_admin_add_form_submit() (line 382 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
Warning: Undefined array key "" in layout_entity_admin_add_form_submit() (line 382 of /var/lib/tugboat/core/modules/layout/layout.entity.admin.inc).
```

**Comment by docwilmot** [comment]
I must confess I'm not highly motivated to work on this. Its been controversial, and I'm foreseeing that there will be more objections and another change in direction. Probably because this is my least favorite approach, and I suspect others may eventually agree when its reviewed.

**Comment by stpaultim** [comment]
@docwilmot - I understand. 

I could try and take over the PR, but I'm a bit nervous about my ability on this one. On the other hand, IF we are close to consensus, then the changes may not be too difficult and I may be able to handle them. 

I feel pretty strongly about this feature (I may have telegraphed that already). I very optimistic that we might have gotten past the objections and controversy already, but by no means certain.

Happy to take this back to a meeting and check to see if we have buy-in from those who have expressed conerns in the past, before asking anyone to put more work into it.

**Comment by stpaultim** [comment]
> Probably because this is my least favorite approach, and I suspect others may eventually agree when its reviewed.

Actually, @docwilmot - can you refresh my memory. Because, I'm not sure anymore which approach you favored. I thought we had included both approaches, rather than picked one over another. What is it that this PR is not doing, that you think it should?

Sincerely interested and a bit confused.

**Comment by klonos** [comment]
> I feel pretty strongly about this feature...

Me too! 🤚🏼 

@docwilmot sorry to see that the process has gotten you frustrated/disappointed to the point that you are now not motivated enough to keep working on it ...I also volunteer to take over the PR and try to polish things, but I might need help/pointers from people more well-versed in the layouts code such as yourself. I hope that the positive comments by @stpaultim and myself are enough to keep you motivated though 🙂

And I, same as @stpaultim, also thought that we last agreed on having a mix of both approaches (the usual "put things where people expect to find them" thing). I will need to go and re-watch the last dev meeting recording when we discussed this (after I figure out which meeting that was that is).

**Comment by avpaderno** [comment]
I checked the preview site, but I did not find anything controversial. I rather think it is a good implementation.  
@docwilmot You did a good job. If you believe there is a better way to implement it, you could express your thoughts. I am sure your thoughts would be considered.

**Comment by klonos** [comment]
> I'm saying that I'm not eager to fix things in *this* PR, because I'm predicting that eventually it may start to get negative reviews. Because I find its a bit weird TBH having all of these layout links and tabs. I may be wrong and everyone may love it, then I'll be happy to finish it.

@docwilmot gotcha 👍🏼 ...although, last I recall, we did have consensus on these links/tabs being a good thing. Anyway, if we end up with some people loving this, while others finding it overwhelming (like contextual links for example, that some people love, while others don't), then may I propose considering a way to enable/disable them? Perhaps a set of checkboxes under Configuration > Administration > Layouts that controls which of these links/tabs are available, and for which entities.

Perhaps we can reduce the amount of "+ Add layout ..." links(?). For example, have the "+ Add layout for all content types" link only be shown under `/admin/structure/types/layout` and not under each individual `/admin/structure/types/manage/%/layouts` path.

Anyway, the above as food for thought. Here's some actual further feedback on the PR:
- I second what @stpaultim said:
  > My expectation when I clicked on "Create a layout for content types" was that I would be given a choice of one or more content types to create a layout for.
- When I clicked the "Create a layout for content types" link, the name that's pre-filled in the form for the layout is ` layout` (notice the space before the word "layout"). There's no error shown and nothing logged though.
- The `types` suffix does not apply everywhere. For example, these do not make sense:
  - "Create a layout for User account types"
  - "Create a layout for Taxonomy term types"
  - "Create a layout for all Taxonomy term types"
- The links should use the verb "add" instead of "create". So, it should be "+ Add layout for ..." instead of "+ Create a layout for ...". That should make them slightly shorter, and be consistent with the "+ Add layout" link in `/admin/structure/layouts` as well as with other "+ Add xyz" links throughout the admin UI.
- The tables with the layouts should be sectioned in the same way as in `/admin/structure/layouts`. In other words, have the "Layout overrides" and "Default layouts" sections + their respective help text where appropriate (which may need some tweaking).
- There should be a "Reorder" button available in the table heading when there's more than one layout, same as in `/admin/structure/layouts`.

In general, perhaps we can re-use the same code that renders the table at `/admin/structure/layouts`, but have various rows/sections that do not apply for the individual "Manage layouts" tabs be `unset()`.

**Comment by stpaultim** [comment]
We are running out of time to get this into the next release. I believe that the current block is a lack of consensus on where to put the UI options for creating and managing entity based layouts. 

We need feedback on whether people feel strong about putting the UI options and manage tab (1) or (2) <see below>. 

Do you feel strongly about YES, listing in both locations or NO, NOT focusing on (1) or (2) and NOT listing it in both locations?

The current PR has them in two locations.

1) On individual content types

![image](https://github.com/user-attachments/assets/52c4c9b9-327e-4e54-80c2-fc6e323da6ae)

2) On the general content type page

![image](https://github.com/user-attachments/assets/be39f595-86bf-44c3-bd2e-6d26c8860d7b)

@docwilmot is understandably reluctant to put much more work into this PR with the interface in both of these locations, if there is likely to be opposition to this in the end. In the last meeting, I understand @quicksketch to be leaning in favor of ONLY listing and creating new layouts on the individual content type pages.

@jenlampton (see: https://github.com/backdrop/backdrop-issues/issues/2894#issuecomment-2166767744) and @klonos have advocated for leaving the UI roughly as it is in this PR, in both places. 

Can we come to a consensus around one of these options before the next weekly dev meeting?

PERSONALLY:

I'm inclined to push for a consensus around the dual location approach in the PR, because I think it's most likely to reach consensus. 

If I had to choose, I would put the links to create layouts on both the individual content type pages and page for all content types. But, I would not necessarily list layouts for each individual content type. I would list layouts for all content types together. 

BUT, I am very much supportive of showing the list in both places. 

I need to be reminded about the arguements against showing the list in both places.

**Comment by olafgrabienski** [comment]
> Do you feel strongly about YES, listing in both locations or NO, NOT focusing on (1) or (2) and NOT listing it in both locations?

While I don't feel strongly about those alternatives, listing them in both locations can make an overwhelming impression which makes it difficult to focus on the most important aspects of the UI. However, the reason for this impression might not be the location(s) where all the links are listed (1 vs. 2). In my opinion, it's rather the space requiring and prominent "Create a layout for all content types" link. Maybe we can find another place for this link or make it superfluous by providing a default node layout?

**Comment by docwilmot** [comment]
I've had yet another idea for yet another UI alternative:

- We get rid of the dedicated pages listing entity layouts, and instead use the existing layout list page `admin/structure/layouts`. But, we filter the visible layouts based on the URL. For example, at `admin/structure/layouts/content` we'd list only `content` layouts and at `admin/structure/layouts/content/page` we'd list all content layouts as well as the default layouts.
- We would keep the `manage layouts` links in the dropbuttons at `admin/structure/types` and in the admin menu, but have those links point to `admin/structure/layouts/ENTITY/BUNDLE`
- On those filtered layout lists we add appropriate action links, such as `Add content layout` or `Add page layout` to replace the `Add layout` action link.
- Clicking those links can take us to the existing `admin/structure/layouts/add` page, or a simplified page with just the template selection icons, or we could do a dialog pop up to select the template and the page title and then go straight into the add block page.
- 
I think this would keep things simple and familiar.
@stpaultim ?

**Comment by stpaultim** [comment]
@docwilmot - I appreciate your thinking creatively about this problem. I think your most recent suggestion is probably closer to what I originally had in mind when I was advocating for this issue. 

The problem I am trying to solve is to make it easy to create entity specific layouts, I'm less worried about adding new ways to manage those layouts. 

Having said that, I do see some advantanges in adding the the ability to manage layouts specific to content types or individual content types. 

In short, I don't object entirely to any of the approaches. If I had to rank them in order of my own preferences. 

1) Your suggestion that we not add new places to manage these layouts. Part of the reason I choose this as my 1st preference, is that I think it's mostly likely to avoid the concerns currently be raised by the other two proposals. 

2) Adding a "manage layouts" option at the entity type level. 

3) Adding a "manage layouts" option at the entity level (ex. all content types). 

4) Adding a "Manage layouts" option eveywhere. I don't dislike this option, but I do see the POSSIBLE/POTENTIAL confusion that some others have pointed out. ;-)

Once again, I see advantages and disadvantages to all of these options and would be happy to see any of them adopted. For me, the inital huge gain is in adding a link/wizard to create these layouts. 

In my opinion, the real problem being solved is making it easy to create an entity specific layout, but the issue is getting bogged down by the question of where to manage these layouts after they are created - which I don't see as nearly as big a problem. To me, we're arguing about which color to paint the bike shed. ;-)

**Comment by docwilmot** [comment]
Hi again @stpaultim as promised, yet another version! Extremely crude PR, pushed just give an idea of what I was thinking here. It was a promising idea in my head but on practice maybe not so much. It doesn't allow a simple way to use field blocks as far as I can see.

What this does is simply add links to the admin bar under content types individual types to manage layouts. Unlike the other PRS this one the link takes you to the existing layout page list with some modifications. I would add further modifications to change the headings and the page title etc but just so you get the picture. Again, lots of funny bugs and and shortcut code, but let me see what you think.

**Comment by stpaultim** [comment]
@docwilmot - I see the PR is still rough and I don't have time to think about it in detail before meeting today. BUT, it's helpful to see roughly how you imagined managing layouts. I'll try to provide more detailed feedback as soon as I can.

**Comment by stpaultim** [comment]
We discussed this issue in the meeting today. @docwilmot was there and there seems to be agreement that the most recent PR was not very helpful. 

Current consensus from those participating in the discussion is to keep the PR focused on a "Manage Layouts" tab in the individual content types with a link that allows for creation of a content type specific layout, with options to either use the existing content block OR to select individual field blocks. 

This does not have a "Manage Layouts" at the entity level (example: for all content types). BUT, we don't see any reason that this can not be added later if people feel strongly about it.

**Comment by docwilmot** [comment]
I've updated the first PR as suggested. https://github.com/backdrop/backdrop/pull/4685. We'll need tests.

**Comment by stpaultim** [comment]
@docwilmot Didn't we still want the content type layout tab to show all layouts that effect content type content, including the default layout. 

In PR 4795 the default layout was included in this list. I think if we are going to have a layout page for each content type, it might be good to show the default layout there. Otherwise this page is pretty empty.

**Comment by stpaultim** [comment]
@docwilmot and I are specifically interested in feedback on how others feel about whether or not to include the default layout on these pages.

**Comment by docwilmot** [comment]
> @docwilmot Didn't we still want the content type layout tab to show all layouts that effect content type content, including the default layout.

FWIW I am not particuarly moved for or against this, but do wonder if having the `default` layout listed confuses things a bit since every other layout will have an `entity` path (like `node/%` or `user/%`). The list could be seen as "a list of layouts with this entity's path" or "a list of layouts that this entity uses". Is it more likely to be considered the former or the latter?

Still, I'll work on putting `default` layout back in meanwhile.

**Comment by jenlampton** [comment]
I do think it would be useful for people who do not have either an all-node or node-type layout. People may be confused if appears as though this page has no layout at all.

Rather than showing nothing on the page, we should indicate that the default layout is in use. This could be done with some text, a simple link back to the layouts section, or by showing the default layout displayed the same way as all the others. Any of those solutions would be fine (and there are probably others that would also work).

**Comment by docwilmot** [comment]
For the table's `empty` text we could do:
> No layout overrides have been created for `!entity_type` types yet. `!entity_types` will be displayed using the `default layout`.

(And link the `default layout` text to the Default layout's block page.

**Comment by stpaultim** [comment]
Here is what @docwilmot put in the current PR.
![image](https://github.com/user-attachments/assets/c8a491eb-74f2-4036-89f8-b81221b33efe)

**Comment by stpaultim** [comment]
I'm happy with this PR. My only minor concern is the "Add content layout". 

![image](https://github.com/user-attachments/assets/f0cb2610-e4ff-4e91-ad09-cc8667014369)

I'm not sure that most folks will understant this one. In a way, all layouts are for content. What is specific about the layout that will be created with this link. This is an option to create a layout for all Nodes or Content Type entities. 

I believe that "Add node layout" would be more accurate and understandable to developers, but I understand that we try to avoid the term "node."

How about "Add layout for all content types"?
or "Add Node layout (all content types)"

"Add layout specifically for all content types"

I don't love any of these options. But, the current label for this link is confusing to me and I think it needs to be improved.

**Comment by olafgrabienski** [comment]
> My only minor concern is the "Add content layout" link.

I agree (also with your suggestions, my favorite is "Add layout for all content types").

Btw, "node" is also used in the empty text and can be replaced by "content", in my opinion.

Before:
> No layout overrides have been created for Node types yet. All Nodes will display using the Default layout.

After:
> No layout overrides have been created for content types yet. All content will display using the Default layout.

**Comment by stpaultim** [comment]
This issue was discussed during the dev meeting today. It was the first issue discussed (for those who want to watch the Youtube recording). The discussion was pretty short and focused on the recent discussion of the 

* Link for "Add content layout"

Others agree that this current label is confusing and it was also suggested that it might be out of context to have this link on this page. The suggestion was that we remove this link from this PR and open a follow-up issue to discuss if and where to include a link to create a layout for all content types.

We don't want a debate about this link to block the rest of this issue.

@docwilmot, @olafgrabienski, @jenlampton and @klonos - What do you think?

**Comment by stpaultim** [comment]
Minor suggestion (this was not discussed at meeting). 

Should be change this text to:

BEFORE:
"No layout overrides have been created for Node types yet. All Nodes will display using the Default layout."

AFTER:
"No layout overrides have been created for Content types yet. All Content types use the Default layout until another layout overrides it."

**Comment by olafgrabienski** [comment]
> The suggestion was that we remove this link from this PR and open a follow-up issue to discuss if and where to include a link to create a layout for all content types.

Sounds good!

**Comment by stpaultim** [comment]
@docwilmot has made another set of changes for us. This is the current PR: https://github.com/backdrop/backdrop/pull/4685

I tested this PR for content types, users, and a vocabulary and can't find any problems. 

For entity types without any extra fields, the "Select individual field blocks" option is not available. Once you add custom fields, this option is available. 
![image](https://github.com/user-attachments/assets/59b2239d-3fba-4c3d-b293-9af22d3be6c0)

User accounts:
![image](https://github.com/user-attachments/assets/48885658-0206-4857-a7a9-6ee7fbb584ce)

Content Types:
![image](https://github.com/user-attachments/assets/eba5f2f3-cc25-46cb-afe7-82c6522ff3d3)

![image](https://github.com/user-attachments/assets/06a0bc2a-0149-4ebe-8aab-e28619d83e1f)

![image](https://github.com/user-attachments/assets/0d3b87b6-bf36-4240-832d-d45e62c45442)

**Comment by quicksketch** [comment]
This looks great! I really like how this works and the way it surfaces the ability to add field blocks. I also like that it brings together the ability to configure a display mode (under Manage Display) and an overall node-page layout (under Manage Layout). I found the whole thing to be intuitive and it seems like the sort of thing that should have been there all along.

I flagged one incorrect message shown when there's no layout added for a particular node type: https://github.com/backdrop/backdrop/pull/4685/files#r1741113906

And this needs test coverage.

**Comment by docwilmot** [comment]
> I flagged one incorrect message shown when there's no layout added for a particular node type
And this needs test coverage.

Working...

**Comment by quicksketch** [comment]
The PR at https://github.com/backdrop/backdrop/pull/4685 was updated by @docwilmot to add test coverage.

I looked through the changes and there are some things that aren't ideal. A fair amount of code is copied out of Layout module's normal `layout_settings_form()` and into `layout_entity_admin_add_form()`. And the code to pull out a bundle label is repeated in 3 separate places. I'll work to clean this up a little bit further.

The good news is the test coverage looks pretty good and they're all passing.

**Comment by quicksketch** [comment]
I cleaned up the code as best I could without doing any really big changes. Still should be passing all tests and (relevant) code style is all passing. This is ready for review.

**Comment by jenlampton** [comment]
I'll give this a test in the sandbox.

**Comment by jenlampton** [comment]
This is really coming along :)

I did find one problem that's pretty major, and that's that when you 1) already have a layout for `node/%` for all node types, and then use the `Add Page layout` link to add a layout, the new layout won't be used. 

That's because the original `node/%` layout comes "first", and the first match will be the one that renders the page. Because the original `node/%` layout matches all node types, it will match, and it will appear as though my brand new layout isn't working at all :(

<img width="1230" alt="Screenshot 2024-09-02 at 10 24 01 PM" src="https://github.com/user-attachments/assets/d03a1ace-8012-4353-aaef-e8a432639b64">

On the Layouts overview page at `admin/structure/layouts` there is a handy "reorder" button that allows you to change the order, so you can fix the problem (assuming you know what the problem is). 

One quick-and-dirty solution would be to add a "reorder" button to this page also. On this node-type only page there's no concept of order, so it makes it less likely that people will know what to do from here, even if we do add a button.

Can we adjust the weight o layouts when they are created, so that a type-specific layout always comes before one with no visibility conditions? I think this would be nice to see globally for all layouts - but it's especially important now that we're exposing this miniature list.

**Comment by quicksketch** [comment]
@jenlampton I updated the PR so that problem should now be fixed. When adding a layout at the same path (i.e. `node/%`) it loops over all current layouts at that path and set the new layout to have a weight one less than the lowest weight, ensuring the new layout always takes effect, even if another layout already exist at the same path. I think this would likely be the expected behavior, especially when there only the generic node layout vs. a type-specific layout.

**Comment by jenlampton** [comment]
It works! 
<img width="1230" alt="Screenshot 2024-09-02 at 10 24 01 PM" src="https://github.com/user-attachments/assets/2fae3438-dd50-4365-87e0-48e5d29c606b">

I've done a quick code review also and everything looks good to me. I found one place where we may need an access check but all other refactoring can be done after code-freeze.

**Comment by quicksketch** [comment]
Access check has been added to the link from the content type. Nice catch @jenlampton!

**Comment by quicksketch** [comment]
It's been a whirlwind to complete this before 1.29.0, but we made it! I merged https://github.com/backdrop/backdrop/pull/4685 into 1.x.

Again, huge props to @docwilmot for his patience and perseverance as we suggested several different approaches in this issue. We appreciate you!

This was a big effort by a lot of people. Thank you @herbdool, @klonos, @stpaultim, @jenlampton, @olafgrabienski, @argiepiano, @bobchristenson, @Graham-72, @hosef, @yorkshire-pudding, and @avpaderno all for your feedback, reviewing, and refinement on the solution.

**Comment by stpaultim** [comment]
Yes, big thanks @docwilmot. As you know, I was very excited about this issue and am so happy that you stepped up and helped with the code.
