### ISSUE TITLE
Module config in /config is not synced on install

### ISSUE THREAD

**Issue by jhodgdon-drp** [backdrop/backdrop-issues#3224]
## Describe your issue or idea

If you create a module and put config in its /config directory, the config is copied to active during module install. However, the sync step is not run.

This leads to an inconsistent state, if the config requires database tables. For example, if a module includes configuration for fields, database tables need to be created for the fields to actually work. These would normally be created during the sync step, but this step is not run, so the field data tables are not created and the fields do not work.

### Steps to reproduce (if reporting a bug)

1. In one Backdrop installation, create a field for a content type.
2. Copy the resulting field bundle and field instance config to the /config directory of a custom module (you might also need the content type it is on).
3. In a second Backdrop installation, install this module.
4. Attempt to create content for the content type including this field.

### Actual behavior (if reporting a bug)

The field will not work correctly. If you try to add content to the content type of that field, you will see the field on the content editing form, but if you save, you will get a database error, because the field data tables do not exist in the database.

### Expected behavior (if reporting a bug)

The field should work correctly. I.e., if you put config in /config for a module, and it is copied to active config storage, the sync step should be run so that the configuration actually works.

### Next Steps

We have a PR that seems to work, but we need someone to write tests. 

---
PR by @docwilmot https://github.com/backdrop/backdrop/pull/3695

**Comment by jenlampton** [comment]
@quicksketch mentioned that always running the sync step might cause problems with the installer. 

I'm envisioning that we may need to add some sort of a flag that modules could use to indicate that the sync step is necessary. Actually, it may be safer to do it the other way around -- allow modules to indicate when the config step does NOT need to be run.

**Comment by jhodgdon-drp** [comment]
I was able to work around this bug with the following hook_install() implementation in my module.

Notes:
- I moved the config files from /config to /config_import within my module directory. 
- To use the config_sync_file() function, currently the core Config Management (config) module must be enabled, so you will have to have a dependency on config in your .info file. See #3226 for details on that.
- I found that doing one import/sync didn't make all the required database tables, so I did a second pass (see comment in code below). This is probably because of config dependencies, which don't formally exist in Backdrop. Maybe there is an order I could run my config sync so that it would all work, but it wasn't obvious to me how to figure that out. However, running the import a second time (again, see code) fixed the problem. (Yes, it's a hack, but it does seem to work, and it's a bit slow but it is a one-time operation when you install the module.)

````
  // Set up config storage objects for the active config and our directory.
  $active_storage = config_get_config_storage('active');
  $directory = BACKDROP_ROOT . '/' . backdrop_get_path('module', 'MY_MODULE') . '/config_import';
  $module_storage = new ConfigFileStorage($directory);

  // Figure out which items need to be imported/updated -- see
  // config_get_statuses().
  $active_files = $active_storage->listAll();
  $module_files = $module_storage->listAll();
  $create_files = array_diff($module_files, $active_files);
  $update_files = array_diff($module_files, $create_files);
  sort($module_files);
  sort($create_files);
  sort($update_files);

  // Perform the updates and imports.
  module_load_include('inc', 'config', 'config.sync');
  foreach ($create_files as $config_file) {
    config_sync_file($config_file, 'create', $module_storage->read($config_file));
  }
  foreach ($update_files as $config_file) {
    config_sync_file($config_file, 'update', $module_storage->read($config_file));
  }

  // Finding the right order to do the imports is difficult. Alphabetical is
  // pretty close, because it means bundles are before fields, which are before
  // instances, but it still doesn't all work correctly. So, as a hack, do
  // them all again as updates to make sure all the database tables are created.
  foreach ($module_files as $config_file) {
    config_sync_file($config_file, 'update', $module_storage->read($config_file));
  }
````

**Comment by jenlampton** [comment]
No PR here yet, removing milestone. (We can add it back into the next bug-fix release as soon as we have a PR)

**Comment by quicksketch** [comment]
Yeah, we'll need test coverage for this change, including a test module that we can enable that adds a new content type and fields automatically on install.

In the PR, I'm also not clear why we need to remove the validation to prevent creating existing fields. Seems like without that check you could get into a situation where that database ended up in an unusual state by partially creating a field until it hit a `table exists` MySQL error. We probably have form validation to prevent that normally, but the intention of the check is to ensure everything is as expected before doing the creation operation.

**Comment by stpaultim** [comment]
Just a reminder that this issue is blocking https://github.com/backdrop/backdrop-issues/issues/3763 [Config Recipes]. 

It is my understanding that the PR works, the only thing needed are tests (see previous comment).

**Comment by docwilmot** [comment]
@hosef are you working on this? Im going to give it a try this weekend.

**Comment by hosef** [comment]
@docwilmot I have not touched this in a while, so feel free to take over.

> Yeah, we'll need test coverage for this change, including a test module that we can enable that adds a new content type and fields automatically on install.
> 
> In the PR, I'm also not clear why we need to remove the validation to prevent creating existing fields. Seems like without that check you could get into a situation where that database ended up in an unusual state by partially creating a field until it hit a `table exists` MySQL error. We probably have form validation to prevent that normally, but the intention of the check is to ensure everything is as expected before doing the creation operation.

As to Nate's comment, I wasn't able to get the file to import correctly without removing the validation check. The code runs that validation multiple times during the process, and if the config file exists when it is run, then it fails and doesn't create the table. This happens even when the file was created by the function checking for validation. In addition, we already check that the config file is new  when saving it the first time. https://github.com/backdrop/backdrop/pull/3568/files#diff-913c922133c9c87badfcc3bf182dd6e5e9212f88ff5015e4d3bd38e8ded51223L297

**Comment by docwilmot** [comment]
I dont think we should remove the validation check, since we dont want fields created by any other means (programmatic, UI, etc) having the same name. 

But in either case if we do the hook invocation before the `config->save()` that solves our problem here anyway and prevents the error.

I'll work on a test or two.

**Comment by docwilmot** [comment]
This works to install a field now, but I'm wondering who should be responsible for cleanup after uninstalling a module. If your module has a `field.field.field_whatever.json` file in config, it will install the field, fine. But if you uninstall the module, the field table will not be deleted. If you try and reinstall, it will try to install the field again, and then you'll get a fatal, that the field table already exists. We could:
- add code that deletes a field table, if it is provided in config, once the module is uninstalled. Thats potential for data loss of course.
- have `field_config_create()` check first if a field table exists before calling `field_create_field()`
- require devs to be responsible for warning and/or cleanup of field tables on uninstall.

Thoughts welcomed please.

**Comment by docwilmot** [comment]
Just went with option 2 above.

**Comment by jenlampton** [comment]
Love it :)

**Comment by stpaultim** [comment]
@docwilmot, @hosef, or @jenlampton - I'm seeing a recent commit that adds tests to this PR. Has this roadblock been cleared yet or are we still working on it?

What are the next steps?

**Comment by docwilmot** [comment]
I've added my recent PR to the issue summary. Tests are in and passing, config is synced and the hook runs. Ready for review.

**Comment by stpaultim** [comment]
I'm trying to do local testing of this PR. I keep getting errors, but I am not sure if the problem is simply the test module I'm using.

Here is repo with my simple test module. Should this be working or is the problem with my module? 

https://github.com/stpaultim/test-recipe

Atten: @docwilmot or @hosef

**Comment by docwilmot** [comment]
Do you have a node type machine name `test`?
Whats the error?

**Comment by stpaultim** [comment]
So,I've been wrestling with this for too long tonight. I'm trying to test the PR by @docwilmot on my local machine, so that I can easily install a custom module as part of the test. 

Here is a copy of the test module that I'm using - https://github.com/stpaultim/test_recipe (@docwilmot - note that I have updated this with your comments). 

When I try to enable this module on a raw 1.x Backdrop site (BEFORE ADDING THE PR) the field is added to the content type but my admin bar disappears. It comes back for a single page load whenever I clear the cache. But, then the admin bar disappears again. It looks the same as this issue, except that turning of aggregation does not help - https://github.com/backdrop/backdrop-issues/issues/4168

On this raw Backdrop 1.x site, I also get the following errors. 

"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.field_data_field_recipes' doesn't exist"

If I start over with a raw site and apply the patch for this PR https://github.com/backdrop/backdrop/pull/3695

And then install the custom module, I do not get any database or PHP errors. I am able to edit a "Post" node and add content to my new field. HOWEVER, the admin bar still disappears on every page load when I've not just cleared the cache.

I also have this Javascript error:

`Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Ra (jquery.js?v=1.12.4:3)
    at Sa (jquery.js?v=1.12.4:3)
    at Function.css (jquery.js?v=1.12.4:3)
    at Object.get (jquery.js?v=1.12.4:3)
    at Function.css (jquery.js?v=1.12.4:3)
    at jquery.js?v=1.12.4:5
    at Y (jquery.js?v=1.12.4:3)
    at n.fn.init.n.fn.<computed> [as height] (jquery.js?v=1.12.4:5)
    at Backdrop.adminBar.behaviors.positionFixed (admin_bar.js?qya02o:155)
    at Function.<anonymous> (admin_bar.js?qya02o:115)`

Here are the high level take-aways. 

1) The Javascript error happens when I enable the custom module with or without the PR. 
2) With the PR enabled, I am able to add the field and edit a node with the new field. I'm not seeing any database or PHP errors. 
3) I've tested with Chrome and Firefox
4) I'm doing all my test with Lando. 
5) I have tried applying the patch to a fresh version of Backdrop AND cloning the PR branch that @docwilmot used for the PR. 
6) @docwilmot was unable to recreate the problem himself earlier this evening. 

I don't see any other reports of the problem with the admin bar in this ticket, so I'm very confused about why this is troubling me.

**Comment by docwilmot** [comment]
> Is there simply an issue with my test module?

Interestingly, this same issue just happened on my laptop. Your field is named `field_test` and there is a test module with that name in Backdrop core. I wonder if thats it. When I rename the field and instance in your config folder to anything else, this stops happening.

**Comment by klonos** [comment]
> ...there is a test module with that name in Backdrop core. ... When I rename the field and instance in your config folder to anything else, this stops happening.

Good find @docwilmot 👍🏼

**Comment by stpaultim** [comment]
@docwilmot - Thanks for finding that, but the bad news is that I had already changed the name of the field last night - see: https://github.com/stpaultim/test_recipe

The field is now = field.field.field_recipes.json
Instance = field.instance.node.post.field_recipes.json

**Comment by docwilmot** [comment]
Youre absolutely right. In this case I have no idea.

**Comment by stpaultim** [comment]
@docwilmot and friends. I figured out the problem. 

Modules require a .module file to be recognized by Backdrop. I included a test_recipe.module file in my test module with an opening <?php and nothing else. Apparently, the <?php was my mistake. I tried removing the .module file and that did not work, but if I left the .module and removed the <?php it works.

**Comment by klonos** [comment]
...I actually noticed that in your repo @stpaultim and was about to suggest that you add at least one function in the .module file. Glad that removing the "empty" `<?php` worked the same 👍🏼

**Comment by stpaultim** [comment]
Anyway. I've tested this on my local laptop and it does as expected as long as the test module contains an empty .module file without without an opening <?php tag. I don't know if this a bug that needs to be fixed or standard expected behavior. 

If we create a "recipe" project type, maybe we can remove the requirement for an empty file? I think that is a follow up issue. 

I'm going to mark this works for me pending any feedback on what I've reported.

**Comment by stpaultim** [comment]
UPDATE:

I've created a more fully featured config recipe module for testing. It creates a simple testimonial content type and view. 

https://github.com/stpaultim/testimonial_recipe

It includes:

- Content Type
- Two new fields
- Three field instances
- Custom image style
- A view of testimonials (/testimonials)

**Comment by docwilmot** [comment]
If that's the case the error should be independent of this PR then. Can you try a test module without the config folder and see?

**Comment by stpaultim** [comment]
@docwilmot - Sure. I just tested the following.

1) I removed all the config files and config directory for my new testimonial recipe module and enabled it without any trouble. Nothing happened good or bad, because there is no code or config in that module
2) I also downloaded, installed, and enabled the devel module with seeing any problems.

**Comment by stpaultim** [comment]
I got clarification from @docwilmot to do a little additional testing to see if we could determine if there was any connection between my earlier problems and this PR. I think we can rule that out. 

First I tested my new testimonial_recipe module both with and without the <?php in the .module file and with and without config files on a site with and without the PR. In none of these cases was I able to recreate the problem with admin bar. 

I then opened a fresh backdrop cms site with my original test module and the problem reappeared. This leads me to believe that there are at least two factors in play with that origin bug. The <?php in the .module file in combination with something else specific to that module. 

I am not sure that this warrants further testing at this time. It would seem that the presence of the <?php might cause problems, but does not always. This is the case with or without the PR.

Does this make sense?

**Comment by quicksketch** [comment]
Thanks @docwilmot again for the updated PR and tests! I pulled this down locally to check further.

I found it a little weird that while we're creating a new field in the tests, we're not actually attaching it to any content type. To make the test more comprehensive I created a new content type manually in the test, bundled an "instance" JSON file in config, then created a new node with data saved into the new field.

I also could not find a clear need for the addition of `backdrop_flush_all_caches()` into `config_install_default_config()`. I left a note on the PR here: https://github.com/backdrop/backdrop/pull/3695#discussion_r698078516

I pushed my changes directly into the existing PR. @docwilmot could you re-review and see if those changes are acceptable?

**Comment by docwilmot** [comment]
> I found it a little weird that while we're creating a new field in the tests, we're not actually attaching it to any content type. 

That is very true. Thanks for fixing that.

**Comment by jenlampton** [comment]
Code looks great, RTBC!

**Comment by docwilmot** [comment]
I've just done another round of testing the weird error, and I am still thoroughly confused. I can consistently still reproduce this and I still cant figure why:
- downloaded @stpaultim's test module, here https://github.com/stpaultim/testimonial_recipe/tree/9727ae24587bb24b0e6ad5229bb7f4c3f06cb0b3. Note he's made changes to the module, and I havent tested this weirdness with the latest code, but its weird enough here.
- make sure you check out this PR
- I've realised I dont even need to install the module, simply place `field.field.field_test.json` and the instance config into the active folder.
- flush caches then reload the page
- admin bar dissapears. (its probably best to test this while youre on the admin/config/performance page so you can just click the clear caches button). It temporarily reappears if caches flush again, but goes again on reload.
- delete the two configs and flush again, admin bar comes back permanently.
- repeat, enjoy, puzzle.
- only happens with that test module. Rename the field configs and it stops happening
- only happens with this PR

I suppose this may be some quirk specific to some common configuration between @stpaultim and I but I'd still like to know why it happens.

**Comment by quicksketch** [comment]
@docwilmot I tried to reproduce as you described, but without luck.

I downloaded Tim's module onto my local copy of this branch and turned on the module. The new field config and tables were created successfully but the admin bar stayed present just fine.

I did not have a "test" node type (on which the new field attaches), but that didn't seem to prevent the tables and config from importing. Once I created a node type with type "test", the new field was already attached and worked fine.

I deleted the test field, uninstalled the module, and re-installed. The field came back again and was usable on the existing "test" content type.

At no time in my testing did the admin bar disappear. @jenlampton also tested (note in the PR https://github.com/backdrop/backdrop/pull/3695#discussion_r698088617) and didn't reproduce it. But based on your description of the problem seeming only to occur with that exact named field, I'd also guess that it may be a specific configuration of your local site that causes the problem.

**Comment by laryn** [comment]
What a huge team effort! I think I'm comfortable saying that the strange error which can't be reproduced (except on @docwilmot's computer) can be a separate issue later if needed... I've merged https://github.com/backdrop/backdrop/pull/3695 into 1.x so this will show up in 1.20.0. Big thanks for the final PR @docwilmot, and the early inspiration @hosef. Thanks for filing the issue and providing a kickstart @jhodgdon-drp, and for all the valuable feedback, code review, and testing @quicksketch, @jenlampton, and @stpaultim!

Recipes here we come! (One minor request, if possible [the first recipe should involve cheddar cheese](https://github.com/backdrop/backdrop/pull/3695#discussion_r698085999).)
