### ISSUE TITLE
[UX] Standardize Label and `machine name` usage in admin listings

### ISSUE THREAD

**Issue by laryn** [backdrop/backdrop-issues#3402]
## Describe your issue or idea

In https://github.com/backdrop/backdrop-issues/issues/3395 the `machine name` value was moved into the `View name` column:

![screen shot 2018-11-30 at 2 57 31 pm](https://user-images.githubusercontent.com/871421/49314481-47c03380-f4b0-11e8-8945-fc5f9c391ac4.jpg)

I've followed that pattern in [recent changes in the Paragraphs module in contrib](https://github.com/backdrop-contrib/paragraphs/issues/23#issuecomment-443291869), and I propose it would be good to use it more broadly in core and make things consistent. We'd first need to get a list of all the pages that list `machine name` as a separate column, but for starters here are some suggestions/questions:

 - all the `Manage fields` pages have separate columns (on content types, user account fields, taxonomy vocabulary fields)
![screen shot 2018-11-29 at 5 30 11 pm](https://user-images.githubusercontent.com/871421/49258853-8ac0cf00-f3fc-11e8-9514-eb74cfccbb3b.jpg)

 - Content types list machine name after the label but include the words "Machine name: " which could maybe be removed:
![screen shot 2018-11-30 at 3 05 38 pm](https://user-images.githubusercontent.com/871421/49314895-82769b80-f4b1-11e8-9961-435b04eb869f.jpg)

 - On the other hand, Taxonomy vocabularies don't list the machine name at all (although it can be useful to have):
![screen shot 2018-11-30 at 3 11 27 pm](https://user-images.githubusercontent.com/871421/49315136-3aa44400-f4b2-11e8-9643-7ebef6bfeca7.jpg)

---

**Final interfaces after the PR:**

Content types list:
<img width="1234" alt="Screen Shot 2021-08-29 at 3 48 28 PM" src="https://user-images.githubusercontent.com/397895/131267767-cbc21e36-f156-4892-b8c7-ecaf4e0f8a77.png">

Taxonomy vocabularies:
<img width="1195" alt="Screen Shot 2021-08-29 at 3 48 49 PM" src="https://user-images.githubusercontent.com/397895/131267768-436ae3c6-d201-417b-9296-752999e1d05a.png">

Custom blocks:
<img width="1212" alt="Screen Shot 2021-08-29 at 3 50 15 PM" src="https://user-images.githubusercontent.com/397895/131267803-49b2582a-d508-47f4-b513-cdf975c64f85.png">

Manage displays:
<img width="1188" alt="Screen Shot 2021-08-29 at 3 51 08 PM" src="https://user-images.githubusercontent.com/397895/131267821-5df1fa22-b80b-4b52-8647-3953f6634ad2.png">

File types:
<img width="1188" alt="Screen Shot 2021-08-29 at 3 51 08 PM" src="https://user-images.githubusercontent.com/397895/131267845-e8c7880a-a14a-4da6-8965-21e4617229a6.png">

**Comment by klonos** [comment]
I think that this is a good idea 👍

**Comment by docwilmot** [comment]
I'm not sure we need to expose the machine name at all, myself. It makes the admin pages just a bit more techie, and I'm not sure thats a good thing. How likely are you to need to know machine names if youre not a dev writing code?

But if we're going to, I'd agree with standardizing how we do it.

**Comment by klonos** [comment]
@docwilmot the machine names are there to help devs. In most places we have them being rendered in a malled font, which decreases prominence. IMO, the views listing does a great job at achieving that by also making the actual name (admin label) bold as well.

**Comment by jenlampton** [comment]
> I'm not sure we need to expose the machine name at all

Even as a non-developer, there are places where you need to know the machine name. I'd love it if this wasn't the case, but we're not quite there yet :)

> It makes the admin pages just a bit more techie, and I'm not sure thats a good thing

This is a good point...

> In most places we have them being rendered in a smaller font, which decreases prominence. 

I was going to say that we should leave the machine name column where we have the room for it, but now that I've read this thread, I don't feel that way anymore. I think by moving it out of it's own column and into the Name/Label/Whatever column, we might make the admin interfaces more friendly (and less techie).

> name (admin label) ...

@klonos you just brought to my attention that we call the Name / Title / Label / Admin Label different things in different interfaces. Is it worth cleaning that up too?

**Comment by jenlampton** [comment]
in https://github.com/backdrop/backdrop/pull/2394/files I noticed the function `theme_views_ui_view_name()`.

We might want to re-purpose that into a more general (system module) name + machine name theme function, and use it universally.

**Comment by klonos** [comment]
@jenlampton I know that as you mentioned in the latest design meeting, as well as previous meetings, you are in favor of modeling this after the Content type listing (`/admin/structure/types`), but I find the style in the Views listing page (`/admin/structure/views`) much more readable/scannable, as it focuses on the human name, and lowers the emphasis of the detail (machine name):

<img width="1179" alt="Screen Shot 2019-08-02 at 8 59 29 am" src="https://user-images.githubusercontent.com/2423362/62347891-f0bda300-b503-11e9-9cf0-638658a6c489.png">

We are using the same pattern in the Layouts listing (`/admin/structure/layouts`), where we need to focus on the layout name, and then also provide the template used as a detail:

<img width="1183" alt="Screen Shot 2019-08-02 at 8 59 42 am" src="https://user-images.githubusercontent.com/2423362/62347899-f61aed80-b503-11e9-9a55-28dc261a39e3.png">

This pattern also works nicely in the Paragraphs listing:

![screenshot from 2018-11-29 09-30-44](https://user-images.githubusercontent.com/871421/49232646-f5045000-f3b9-11e8-9833-66c5b5894878.png)

**Comment by klonos** [comment]
> @klonos you just brought to my attention that we call the Name / Title / Label / Admin Label different things in different interfaces. Is it worth cleaning that up too?

Yup, I think that we could squeeze that in too 😄

**Comment by jenlampton** [comment]
> it focuses on the human name, and lowers the emphasis of the detail (machine name):

Hm, that is exactly what I was trying to achieve with the machine name smaller, lighter, and in parens. I think the only difference is hat the content type page has it all in one line, and these other pages have it in two.

<img width="1195" alt="Screen Shot 2019-11-21 at 12 13 22 PM" src="https://user-images.githubusercontent.com/397895/69373312-6044d300-0c58-11ea-96c0-60a33e6fb087.png">

We could solve that problem with a class on the outer wrapper, the markup within can be identical :)

**Comment by jenlampton** [comment]
I've filed a PR for this that adds a new universal theme function `theme_admin_info()` that will display the name, machine name, and description (if provided). By incorporating all 3, I was able to update X different admin interfaces to all use the same function, and the end result makes me really happy :) 

> Other places to consider?

* Node types listing
* Layout listing
* File types listing
* Taxonomy vocabulary listing
* The menu listing
* The image style listing
* The text format listing
* The date format listing

Deprecated functions:

* The function theme_node_admin_overview() is marked as deprecated.
* The function theme_file_type_overview is marked as deprecated.
* The function `theme_menu_admin_overview()' is marked as deprecated.

I think we could also use this improve the views UI, but I thought that was too big of a can of worms to tackle as part of this issue. Photos below!

Node types listing
<img width="1223" alt="nodes" src="https://user-images.githubusercontent.com/397895/80323477-73983380-87e0-11ea-9883-26bc612eb3cd.png">

Layout listing
<img width="1222" alt="layouts" src="https://user-images.githubusercontent.com/397895/80323485-7a26ab00-87e0-11ea-8403-bd1ae3b55899.png">

File types listing
<img width="1216" alt="files" src="https://user-images.githubusercontent.com/397895/80323492-83177c80-87e0-11ea-88b6-989113c21ccc.png">

Taxonomy vocabulary listing
<img width="1245" alt="taxonomy" src="https://user-images.githubusercontent.com/397895/80323498-89a5f400-87e0-11ea-9fa6-a360ee7f1243.png">

The menu listing
<img width="1228" alt="menus" src="https://user-images.githubusercontent.com/397895/80323501-90cd0200-87e0-11ea-8c02-290252cdeb19.png">

The image style listing
<img width="1237" alt="image-styles" src="https://user-images.githubusercontent.com/397895/80323503-962a4c80-87e0-11ea-99ff-e78852accee5.png">

The text format listing
<img width="1235" alt="text-formats" src="https://user-images.githubusercontent.com/397895/80323506-9e828780-87e0-11ea-9ed9-dd247c8faaf0.png">

The date format listing
<img width="1224" alt="date-formats" src="https://user-images.githubusercontent.com/397895/80323512-a80bef80-87e0-11ea-86bd-483fb74d4d33.png">

**Comment by docwilmot** [comment]
3 thumbs up. Nice.

**Comment by docwilmot** [comment]
Tested (works for me) and milestoned.

**Comment by docwilmot** [comment]
Related: when doing things with permissions you can hover over the row in the permissions table to get the "machine name" of the permission but is it worth having that more visible, similar to this PR? I know the permissions table is already a bit of a beast. Not for PR but it just came to mind wanted to see if this was worth an issue or if we prefer to leave that poor table alone.

**Comment by quicksketch** [comment]
Code review: https://github.com/backdrop/backdrop/pull/3128#pullrequestreview-400575782

**Comment by jenlampton** [comment]
feedback in PR addressed, rebased and pushed an upadte.

**Comment by BWPanda** [comment]
I applied the PR/patch to my local site running the latest 1.x version of Backdrop, and when I did, on the pages shown above, the first column was empty:

![image](https://user-images.githubusercontent.com/2385329/91439633-a5b1c300-e8b0-11ea-8dae-f709c8b45bde.png)

I'm marking this as 'needs work' as a result (also, there are test failures).

Additionally, I have a concern:
The new design/layout of these columns means the first column is quite cluttered (3 bits of information in there: label, machine name and description). This looks most obvious on tables where there's not much other information. E.g.:

![image](https://user-images.githubusercontent.com/397895/80323501-90cd0200-87e0-11ea-8c02-290252cdeb19.png)

I recommend moving the description to its own column and the machine name below the label, basically like Views currently does:

![image](https://user-images.githubusercontent.com/2423362/62347891-f0bda300-b503-11e9-9cf0-638658a6c489.png)

My reasons for this are:

1. It removes the clutter from the first column, spacing out the available information, and
1. It means that the description column can be hidden on smaller screens, since it's generally not as important. Currently there's no way to hide this and so that first column with all its clutter will always be visible, even on small screens where unnecessary information should be hidden for better UX.

**Comment by klonos** [comment]
> It means that the description column can be hidden on smaller screens, since it's generally not as important.

Good thinking there 👍

**Comment by jenlampton** [comment]
Can we add the separate Description column in a follow-up ticket? 

This ticket is to crate a single theme function that will always output Label, Machine name, and Description in the same way. It will be easy enough to remove `Description` from the calls to this function in the next ticket, and add another column into these tables to display only description. It shouldn't block the creation of this new theme function though.

**Comment by BWPanda** [comment]
> This PR crates a single theme function that will always output Label, Machine name, and Description in the same way.

If we intend to move the description out in a later issue, is the a point to committing this with it included then? What use-cases are there for keeping the description in the same column as the label/machine name?

> Looks like maybe you didn't rebuild the theme registry?

I previously cleared all caches after applying the patch (both via the admin bar and with `drush`). I just tried again and specifically selected 'THeme registry' from 'Flush all caches' in the admin bar - no change. Tables still display with empty first column...

I won't set back to 'needs work' again in case it's just something specific to my site, but there are still test failures.
@jenlampton Can you please refresh the PR to initiate a new sandbox with the latest changes? Then I can test there instead and also see if that fixes any tests.

**Comment by BWPanda** [comment]
Also, it looks like @quicksketch's reviews were marked resolved, but without all changes being applied, or an explanation given as to why not. E.g.: https://github.com/backdrop/backdrop/pull/3128/files#diff-4069bef0c8037fa96f53813774940102R527

**Comment by herbdool** [comment]
Tests failing so needs work.

**Comment by BWPanda** [comment]
I've made a new [PR](https://github.com/backdrop/backdrop/pull/3473), based on @jenlampton's, but with the following changes:

- Renamed the new theme function to `label_machine_name`
  This is because the main purpose of the theme function is to output a label, in both human-readable and machine-name formats. Also, the machine name is less important as it's displayed in a smaller font. So I figured the word 'label' should come first.
- Renamed the `machine` variable in the new theme function to `machine_name`
- Removed the `description` variable from the new theme function
  Descriptions are not as important as the labels, and are often longer. They should therefore be displayed in a separate column; for better readability (having too much information in one column makes it hard to read/scan), and so that column can be hidden on small screens (to be done in another issue as appropriate).
- Removed the `inline` variable from the new theme function
  With the Description displayed in a separate column, the machine name can be displayed below the label. This makes the human-readable label stand out more and allows for easier scanning of tables. It also allows more room for the text `Machine name:` to be displayed before it (useful when the label and machine name are the same (e.g. 'Tags')).
- Added a `link` variable to the new theme function
  Some places where this will be used require the labels to be linked to the item in question (e.g. `/admin/config/media/image-styles`), so this optional variable allows for that. Or do we not want labels linked at all now...?
- Replaced the `<strong>` tags around the human-readable label with `<div class="label"></div>`
  It makes for easier (sub)themeing if there's a named class around the label, rather than a hard-coded `<strong>` tag.
- Replaced the `<small>` tags around the machine name label with `<div class="machine-name"></div>`
  For the same reasons as above.
- Added CSS to the System module to display the machine name smaller, and to the Seven theme to display the label as bold and the machine name as grey
- Added better `@deprecated` text
  It now mentions the new theme function and that descriptions have been moved to a new column (where appropriate).
- Updated additional forms
  Such as node Manage Fields, and Layout Templates.

PR still needs work as there are more forms I need to update (such as node Manage Displays), I just ran out of time tonight.

**Comment by BWPanda** [comment]
I've removed the milestone as I don't believe any of these PRs will get in this next release. Happy to add to the 1.18.1 milestone once that's created.

**Comment by BWPanda** [comment]
I've updated my PR with more forms/pages. I think I got them all...

**Comment by BWPanda** [comment]
You can check the Tugboat sandbox to see all the different pages that have been updated, but here're two quick screenshots:

![image](https://user-images.githubusercontent.com/2385329/103491770-80dee500-4e7a-11eb-928a-6d066be4e91c.png)

![image](https://user-images.githubusercontent.com/2385329/103491776-8c321080-4e7a-11eb-8cf9-efb09168e908.png)

**Comment by klonos** [comment]
Thanks @BWPanda for reviving this issue; it's one of my favorites 🙂 ...and may I add: excellent job on the PR too! 👏 ...I especially like how you've taken care to add double-underscore `__` implementations, so that it's easier to theme a specific admin page 👍 (I keep forgetting how useful that can be, and how powerful theming is in Drupal/Backdrop)

Feedback:
- Should the label and machine name be `<span>`s instead of `<div>`s? (I think so) ...I know that having them as divs makes them stack on top of each other w/o any CSS, but perhaps semantically it makes sense to have them not be "divisions" (they are both inside the same table cell or "section").
- Having a link option for the label doesn't hurt (so I think we should still keep it in the theme function, for more theming flexibility/options), but if we are to redirect to edit forms for the specific item, don't we have the "Operations" links as a UI pattern for that?
- Perhaps include a new variables in the theme function, to allow for things like:
  - the label link (default it to `$label_link = NULL`)
  - wrapping label and machine name in div or span (default it to `$wrapper_element = 'span'` or `$render = 'inline'`)
  - prepending the `Machine name: ` bit or not (`$machine_name_label = t('Machine name') . ': '`)
- Re moving the template name/link to a separate column in the layout listing, I'm not opposed to it, but doesn't it feel a bit odd to have the template name/link in a column, while the preview thumbnail for the template is still in the "name" column (and btw, that thumbnail is also a link to the same page as the text version of the template name)? 🤔
- I've left a suggestion in the PR re (re)using `layout_get_layout_template_info()` within a `foreach`.

Thanks once again for your excellent work on this 👍

**Comment by klonos** [comment]
...we still have a couple more weeks till 1.18.0, and a 1.17.5 may be released at any time between now and Jan 15 😉 ...besides, I feel that this is really close 🙂

**Comment by klonos** [comment]
...another minor thing with the content type display modes page:

![image](https://user-images.githubusercontent.com/2423362/105140995-28a61500-5b01-11eb-9c8a-9115efebd53f.png)

^^ I'm fine with making everything else in the default display mode row prominent by bolding it, but the machine name feels like shouldn't be bolded.

**Comment by jenlampton** [comment]
Thanks @BWPanda for all the work on the PR! I think most are improvements, but have a few concerns...

> Removed the description variable from the new theme function

This was added because there were places in core that included the description in the same markup. The goal was to introduce a function that solved all the needs of core and changed as little as possible.

Maybe the goal has changed and now we want to make all these pages identical. I'm actually in favor of that too :)

> Removed the inline variable from the new theme function

Same reasoning here. (I was trying to change as little as possible.)

> Some places where this will be used require the labels to be linked to the item in question (e.g. /admin/config/media/image-styles), so this optional variable allows for that. Or do we not want labels linked at all now...?

Well, we either need to remove this variable so everything is the same, or add the all others back so we can have the variations where they are now. We shouldn't arbitrarily include some things but not others. 

I'd vote for removing the link on image styles since the first drop-button goes to the same place.

> Replaced the `<strong>` ... Replaced the `<small>` ... Added CSS to the System module

Using `<strong>` and `<small>` was a trick to avoid breaking people's sites by changing the CSS out from under them. If we want to change the CSS, then this issue will also end up depending on https://github.com/backdrop/backdrop-issues/issues/4167, which I was trying to avoid. 

`<strong>` and `<small>` are semantic, which is usually seen as "better" than using classes.  However, since we already use the `label` and `machine-name` class in other places, I do like the consistency of using them here.

> Should the label and machine name be `<span>`s instead of `<div>`s? 

@klonos we have the same problem here about changing CSS.

> Perhaps include a new variables in the theme function

I'm against adding more variables. If we are going to standardize on something, It shouldn't have very many options. If people want to do something else, they can override the theme function for their specific use-case.

**Comment by jenlampton** [comment]
Re CSS changes: I grep'd through core and didn't find any other uses of the `machine-name` or `label` class, which is weird. I could have sworn I'd seen that before, but maybe not?  Anywho... since we apparently weren't using those before, then the changes to `system.css` won't affect any existing sites (and changes to seven are minimal) so I have no further objections to moving forward with this approach :)

@klonos I share your concern about the layout listing, but that UI is a special case, and is getting attention in other issues right now. I don't think that should hold up this issue.

@BWPanda what are your thoughts on div vs span?

Remaining changes:
* remove the link variable from the theme function
* switch `<div>`s with `<spans>`?

**Comment by BWPanda** [comment]
> I especially like how you've taken care to add double-underscore __ implementations

That was @quicksketch's suggestion in @jenlampton's PR. I just inherited it 🙂 

> what are your thoughts on div vs span?

I don't think using a `<div>` is *wrong*, so I'd be fine leaving it for now and then seeing if people request a change in future (by then maybe the whole CSS changes in core thing will be figured out...).

> I'd vote for removing the link on image styles since the first drop-button goes to the same place.

I've been wondering about this since I first made the PR, and I agree. Image styles are the only place in core (that I noticed) where the label linked to the 'thing'. But since we have the drop-button for that anyway, let's remove the label link (and therefore the option to add links in this new theme function).

> I'm fine with making everything else in the default display mode row prominent by bolding it, but the machine name feels like shouldn't be bolded.

Agreed. Fixed.

> Maybe the goal has changed and now we want to make all these pages identical. I'm actually in favor of that :)

Yes, that's been my assumption/intention here. Consistency FTW!

@klonos posted a comment in the PR that I think should be discussed here:

> I'd prefer if the machine name "prefix" was optional. Perhaps another machine_name_prefix variable, with a default value of t('Machine name')? ... Perhaps even allow NULL, in which case the prefix would be omitted entirely, and only the actual machine name would be printed.

In response to that I say that we're trying to go for consistency here. Are there examples where the 'machine name' prefix isn't appropriate? What does @jenlampton think?

I *think* I've addressed all the deeback. PR updated. Ready for review again!

**Comment by jenlampton** [comment]
> Are there examples where the 'machine name' prefix isn't appropriate? What does @jenlampton think?

There are a few places in core that don't have the prefix (Views UI comes to mind), and I found those interfaces confusing. I would prefer that we always provide the prefix, so that people know what this parenthetical thing is.

**Comment by klonos** [comment]
I'm loving the amount of clean-up and standardization in this issue! ❤️ ...awesome work @BWPanda 👍 

One final thing I caught is this regression where the column contents in the Field manage UI have shifted...

Before:

<img width="50%" height="50%" src="https://user-images.githubusercontent.com/2423362/105332347-33ce7300-5bdd-11eb-848f-e335fd6e28ff.png">

After:

<img width="50%" height="50%" src="https://user-images.githubusercontent.com/2423362/105333025-ebfc1b80-5bdd-11eb-9d55-ada142254d98.png">

So I guess we'll need to move the machine name under the new field label field. Quick mockup:

<img width="50%" height="50%" src="https://user-images.githubusercontent.com/2423362/105334758-eacbee00-5bdf-11eb-9f0b-a85d7edbd49d.png">

**Comment by BWPanda** [comment]
Ok, had a crack at this and think I got it working. PR updated.

**Comment by klonos** [comment]
Hmmm 🤔 ...I don't think I like the implementation with a "blank" column for the machine name, w/o any heading. When editing the machine name, it just seems "disconnected" from the rest of the elements on the table.

Before:

<img width="50%" height="50%" src="https://user-images.githubusercontent.com/2423362/105378710-c0e0ee80-5c14-11eb-9ddc-765584970b5f.png">

- the table heading was visually acting as a "label" for the machine name field
- the rest of the machine names in the same column were also helping to visually "connect the dots"
- on mobile, we'd have an additional column that would need to remain visible (high priority), and increase the requirement of horizontal space (would "squeeze" things horizontally)

After:

<img width="50%" height="50%" src="https://user-images.githubusercontent.com/2423362/105378748-cb02ed00-5c14-11eb-9f0b-7b8514eecb38.png">

Also, having the machine names of existing fields moved in the first column with the respective field label vs. machine name of the new field in a separate column makes it seem inconsistent.

**Comment by jenlampton** [comment]
Field UI is a pretty complicated interface. Maybe we should leave this one as-is instead of converting to our machine name theme function. Get that improvement in, and revisit this with fresh eyes.

**Comment by klonos** [comment]
> Maybe we should leave this one as-is instead of converting to our machine name theme function.

I really like the consistently-looking label/machine-name pair though 😞 

I don't think that editing the automatically generated machine name is that common; and even if so, I don't see why it deserves an entire column in the Field UI 🤷 ...comparing the current UI to the 3rd screenshot/mockup from [my comment](https://github.com/backdrop/backdrop-issues/issues/3402#issuecomment-764520254), I find it to be an improvement.

Anyway, I would hate to delay this getting in, so perhaps if this starts being dragged for too long, we can split the Field UI to a separate issue(?).

**Comment by jenlampton** [comment]
Hm, I edit the machine name almost every time to add the bundle name.

It has its own colmn because it takes up a lot of space. Two textfields
side by side would be a huuuge column (this us what the machine name form
element does) and two fields above one another would be too much vertical
space, making this page unnecessarily long, especially for bundles with
lots of fields.

This isn't a great UI to start with, but it's functional.

**Comment by BWPanda** [comment]
In order not to hold us this issue, I'd be OK with reverting all the PR changes to this page, then opening (or updating) a separate issue for fixing this page - maybe a separate table for the add fields, or a different UI altogether...

**Comment by BWPanda** [comment]
PR has been updated to revert (most of) the changes to the Manage Fields page. I kept the changing of the markup for field labels to using the new theme function, since that can still happen without the machine name being included.

I'll open a new issue about the Add Field UI, since I couldn't find any existing ones that just focused on that.

**Comment by klonos** [comment]
> Two textfields side by side would be a huuuge column

My mockup has the machine name thingy under the label field (consistency with the existing fields). The goal was to keep it there also when in edit mode. That'd make the two fields stacked on top of each other, so the column wouldn't be wide.

> or a different UI altogether ...I'll open a new issue about the Add Field UI, since I couldn't find any existing ones that just focused on that.

There's #779

**Comment by BWPanda** [comment]
> There's #779

Yes, I'll be adding to new issue to that meta as a checkbox, but this issue will be very focused, while that meta in general is quite broad in scope and, in my opinion, not likely to get completed any time soon.

> That'd make the two fields stacked on top of each other, so the column wouldn't be wide.

@jenlampton also addressed that with her comment:
"and two fields above one another would be too much vertical space, making this page unnecessarily long, especially for bundles with lots of fields."

**Comment by BWPanda** [comment]
Status of this issue? Can we get a review of the PR?

**Comment by klonos** [comment]
@BWPanda there are still test failures and needs to be rebased.

The changes in `core/modules/field_ui/field_ui.theme.inc` account only for Node, whereas they should be for all entity types. I've filed a PR against your branch here:https://github.com/BWPanda/backdrop/pull/14 (the actual changes I'm proposing are in https://github.com/BWPanda/backdrop/pull/14/commits/5b5e625ebcd4814b62f177898e846f49e2881f58)

**Comment by klonos** [comment]
...also not sure that the "required" indicator for anon and authenticated roles in ??? now seems that it gets too much prominence:

![image](https://user-images.githubusercontent.com/2423362/117027615-8a336d80-ad05-11eb-9560-3b47d6789d9f.png)

(and I don't thing that "Status" for the column header is appropriate, but don't have any suggestions at the moment 🤔 )

...for reference, here's how these indicators are currently implemented:

![image](https://user-images.githubusercontent.com/2423362/117027900-d2eb2680-ad05-11eb-858c-64efe59c1123.png)

**Comment by klonos** [comment]
Thanks @jenlampton ...I've fixed the issue with the padding being added in all tables, but I need some pointers as to how to make the `.label` selector more specific. Would `table .label` work, or still too generic? ...should we be wrapping the label and machine-name divs in another div, and then use that div to target them specifically? If so, then what would be a good name for the class of that wrapper div?

**Comment by jenlampton** [comment]
> ...should we be wrapping the label and machine-name divs in another div, and then use that div to target them specifically? If so, then what would be a good name for the class of that wrapper div?

I hate to add more divs... I think `table .label` would be sufficient. In a perfect world all these tables would have a class `admin-table` (or something), but this should work for now.

**Comment by klonos** [comment]
> Fixing the padding also cleaned up the appearance of the `node/add` page already!

Yup, it removed the padding there, but not the boldness of the labels. Adding CSS specificity next, which should fix that too...

**Comment by klonos** [comment]
...that's done, and it seems to be working. Fixing tests next.

**Comment by klonos** [comment]
Failing tests fixed. This is ready for a final review/testing.

PS: there are now 2 instances of zenci/undeploy checks in the PR; one passed, and one failed 🤷🏼 ...I'm done with trying to close/reopen to satisfy Zen CI (done it 6 times) 😓

**Comment by klonos** [comment]
...pushed another minor change, and this time Zen obliged me 😅

**Comment by jenlampton** [comment]
the new PR looks great! I think some changes from our tabledrag problem today might have snuck in though. I also asked 2 questions on the PR.

**Comment by klonos** [comment]
Thanks @jenlampton. Can you please see my replies in the PR comments and let me know if you still think that there's changes that need to be made?

Last thing to consider: should we keep this theme/style change specific to labels when they are paired with machine names, or make it more generic? For instance, I was thinking that it could be reused in the recently-added telemetry metrics listing:

![image](https://user-images.githubusercontent.com/2423362/131250266-9f6f7ae9-cd6b-4b15-a331-f6dd7d6e54ce.png)

...I understand that this would most likely mean that `theme_label_machine_name()` would need to be renamed (as well as all the theme suggestions in the PR derived from it), in which case, what would be a good, generic name for it? These are the alternatives I came up with (don't like any of them 😓):
- `theme_label_details()`
- `theme_label_subtitle()`

edit: how about `theme_label_with_caption()` or `theme_label_with_legend()`?

Also trivial, but this issue started as a CSS/style standardization task, but has evolved to introduce a new theme function (although updating all listings to use it still sounds like a task). Should we change the label to `type - feature`, and move it to the 1.20 milestone?

**Comment by jenlampton** [comment]
It's not a new feature, just happens to include a new function, but if a
core committer wants to add it to 1.20 instead of 1.19.4 that's fine :)

I also don't think we should change the name this late. We can alter the
output of the telemetry form later, if needed.

**Comment by klonos** [comment]
Update: I just had a chat re my previous comment with @quicksketch in the sprint zoom room. The preference seems to be to leave the function we've added here be specific to the labels + machine names combos. If we needed to have the same or similar styling with other things, then that/those should be different theme functions. But we only have that single use case of the newly-added telemetry metric listing for now, so not worth it adding a theme function only for that.

> It's not a new feature, just happens to include a new function, but if a core committer wants to add it to 1.20 instead of 1.19.4 that's fine :)

Agreed 👍🏼 

@jenlampton I believe that I've addressed all concerns. The only thing remaining now is the font-`size: smaller;` thing. Let me know if you need that changed to a specific value, and let's try wrap this up for 1.94/1.20 🙂

**Comment by jenlampton** [comment]
@klonos thanks for answering my questions -- code review checks out! Testing one final time now :)

**Comment by jenlampton** [comment]
I posted screenshots from the final test at the bottom of the Original Post. RTBC!

**Comment by quicksketch** [comment]
@klonos and I discussed this earlier during the code sprint and my recommendation was to not attempt to share the "machine_name" theming with any non-machine name situations (such as the Telemetry page). We're already consolidating 5-6 theme functions and that's great, but in all cases they're machine names. If we want to have a second theme function for label + description situations that are not machine names, let's separate that into a different issue.

**Comment by laryn** [comment]
Note: I just merged https://github.com/backdrop/backdrop-issues/issues/2029 which may have caused an issue here so we should double check.

**Comment by klonos** [comment]
Thanks for letting us know @laryn 👍🏼 ...I'll check and update as/if necessary shortly.

**Comment by klonos** [comment]
...fixed merge conflicts: [`406b564` (#3710)](https://github.com/backdrop/backdrop/pull/3710/commits/406b564d023835c75dc967f5ff1c902ad611b8e1)

**Comment by klonos** [comment]
...final nit-picking for more consistency:

Most tables use "Name" for the column header of the things, besides:
- layouts (`admin/structure/layouts`), where the column header is "Path and layout"
- layout templates (`admin/structure/layouts/settings`), where the header is "Template"
- menus (`admin/structure/menu`), where the header is "Title"
- blocks (`admin/structure/block`), where the header is "Block"
- vocabularies (`admin/structure/taxonomy`), where the header is "Vocabulary name"
- manage displays (`admin/structure/types/manage/%/display`), where the header is "Display modes"
- image styles (`admin/config/media/image-styles`), where the header is "Style name"

So, should we have the table header be:
- plain "Name" everywhere (besides layouts - since its a special case, with the table having multiple headers)
- the actual name of the thing ("Menu", "Content type", "View", etc.)
- a combination of the name of the thing + the word "name" ("Menu name", "Content type name", "View name", etc.)

Do we want the modules listing to also have the same style? Follow-up, or do it here?

**Comment by jenlampton** [comment]
> Follow up, or do it here?

I think I already made a follow up for this, checking...

**Comment by jenlampton** [comment]
@klonos, I found the PR closed (but not merged) so I re-oepened it. I think the closing was a mistake. I did a final review though, and it looks great!

**Comment by klonos** [comment]
> I found the PR closed (but not merged)...

Yeah, I was trying to get Zen CI to cooperate again ...closed it, but then forgot to come back and enable it. Thanks for that 👍🏼

**Comment by klonos** [comment]
I've just rebased with latest 1.x, and GHA tests are green 🎉

**Comment by laryn** [comment]
> Also trivial, but this issue started as a CSS/style standardization task, but has evolved to introduce a new theme function (although updating all listings to use it still sounds like a task). Should we change the label to type - feature, and move it to the 1.20 milestone?

> It's not a new feature, just happens to include a new function, but if a core committer wants to add it to 1.20 instead of 1.19.4 that's fine :)

It's a bit of a grey area but I think since we're so close to `1.20` this feels like a good feature to add there: 77 comments later, I've merged into `1.x` using https://github.com/backdrop/backdrop/pull/3710 in https://github.com/backdrop/backdrop/commit/1d2996c48e1849fcafa664eeacb093451556039c. Thanks for all the iterations, feedback, testing, and code review! I've tried it out in the sandbox and really like the visual consistency -- great work @klonos, @jenlampton, @BWPanda, @quicksketch, @docwilmot, and @herbdool.

**Comment by laryn** [comment]
Opening again -- where does this need to be documented?

**Comment by jenlampton** [comment]
We should add a new change record on docs.b.org announcing the addition of the theme function.

**Comment by jenlampton** [comment]
Change record is here: https://docs.backdropcms.org/change-records/theme_file_type_overview-deprecated-in-favor-of-theme_label_machine_name

**Comment by quicksketch** [comment]
Thanks for cross-referencing these issues! At this point I don't think we can revert the related PR entirely, since it's already included in 1.20.0. Let's use the new issue at #5293 to work on remedies.
