### ISSUE TITLE
Do core updates via the UI run well?

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop/backdrop-issues#3433]
In #3105 we added core updates via the UI, and in #3271 we're planning to expose the currently hidden feature to people.

I've tested the UI core update a couple of times, and most of the times it went well. Recently I had an issue on one testing site (see comment below), and I think it makes sense to collect information about how well the UI core update is running and in under which circumstances it doesn't run.

Every test scenario is welcome. An important scope of the issue is however to get an impression how the UI core update is running in the real world, primarily in different hosting situations.

----
PR: https://github.com/backdrop/backdrop/pull/2431

**Comment by olafgrabienski** [comment]
On one of my sites, when I try to update Backdrop via the UI to 1.11.3, I get the following error:

> HTTP error -1 occurred when trying to fetch https://github.com/backdrop/backdrop/releases/download/1.11.3/backdrop.zip.
> Downloading updates failed: Failed to download backdrop from https://github.com/backdrop/backdrop/releases/download/1.11.3/backdrop.zip

AFAIK, on the same site, I could update to 1.11.2 via the UI without any problem.

**Comment by stpaultim** [comment]
Can anyone provide any suggestions on how to best test this feature? 
I assume I need to enable it on a prior version of Backdrop so that it has something to update to.

**Comment by olafgrabienski** [comment]
@stpaultim Yes, you need to have an older version to update from. And, for the time being, you have to enable the feature in the `installer.settings.json` configuration file.

**Comment by serundeputy** [comment]
@stpaultim here is a way to automate the grunt work of testing updating.

```bash
#!/bin/bash
set -ex
set -ex

git clone git@github.com:backdrop/backdrop.git 414automaticUpdates
cp 2289.patch 414automaticUpdates/
rm 2307.patch
wget https://github.com/backdrop/backdrop/pull/2307.patch
cp 2307.patch 414automaticUpdates/
cp .lando.yml 414automaticUpdates/
cd 414automaticUpdates/
git checkout 1.10.2
git apply 2289.patch
git apply 2307.patch
lando start && lando drush si --db-url=mysql://backdrop:backdrop@database/backdrop
lando drush uli

```

however in #414 the powers that be took a diff turn with the UI by  introducing https://github.com/backdrop/backdrop-issues/issues/3271 ... so that script will get you the  things ... but  you'd need to update for #3271, but it is fine for testing this issue as is.

**Comment by stpaultim** [comment]
I tested using the script above (with a few tweaks). It seemed to work the first time, on two subsequent tries I got white screen during installation process with this error. 

Backdrop v 1.10.2 
2307.patch
2289.patch

`Warning: require_once(/app/core/includes/bootstrap.inc): failed to open stream: No such file or directory in /app/index.php on line 19 Call Stack: 0.0013 368080 1. {main}() /app/index.php:0 Fatal error: require_once(): Failed opening required '/app/core/includes/bootstrap.inc' (include_path='.:/usr/local/lib/php') in /app/index.php on line 19 Call Stack: 0.0013 368080 1. {main}() /app/index.php:0`

**Comment by stpaultim** [comment]
I used the script provided by @serundeputy with a few hacks. I checked out v. 1.11.0 and applied #3271 instead of the two patches he listed. 

My first attempt failed, because I did not do anything with permissions. On my second try, I used the looser permissions described here: https://backdropcms.org/file-permissions-and-ownership

I got the same message that @olafgrabienski described: 

`HTTP error -1 occurred when trying to fetch https://github.com/backdrop/backdrop/releases/download/1.11.3/backdrop.zip.
Downloading updates failed: Failed to download backdrop from https://github.com/backdrop/backdrop/releases/download/1.11.3/backdrop.zip`

**Comment by olafgrabienski** [comment]
My issue to update one of my sites over the UI -- see https://github.com/backdrop/backdrop-issues/issues/3433#issuecomment-447926679 -- is solved: There was a problem with `wget` being extremely slow on the server. A manual `wget` download of the core ZIP needed more than two minutes. When the hosting company had fixed this problem, the update via the UI went smoothly as expected!

I guess, the slow `wget` is a perfect explanation for what I've experienced so far:

- I had updated core before, on this site, without any issue. Probably, at that time `wget` just ran fine.
- This time, while updating core didn't work, I was still able to update a contrib module, probably because the module was quite small compared to core, so that the slowness wasn't an issue.

Does anybody know if `HTTP error -1` has a specific meaning related to timeout problems? If so, we could provide a more meaningful error message to help people to identify such an issue.

**Comment by olafgrabienski** [comment]
In the meantime, I've updated two other Backdrop sites (with different hosting situations) via the UI without any problem.

**Comment by stpaultim** [comment]
I just spun up a version of Backdrop 1.11.0 in my Lando environment and tried the update process. I got the same "UpdaterException" error message as in https://github.com/backdrop/backdrop-issues/issues/3433#issuecomment-448097459. 

I tried updating a module through the UI and was successful. I installed an older version of devel and then updated it through the UI. 

Could my problem be Lando related? Will try in a different environment.

**Comment by stpaultim** [comment]
I've been a little unsure of where to post the results of my tests (hence posting in #3271 as well as here). I am inclined to believe that I'm doing something wrong which may or may not be relevant, because I can't get this to work at all. 

Using the process above, but without applying the patch and simply manually changing `core_update` (json file) to `1` or `true`, I was still unable to get the update to work. 

I would appreciate any ideas on how I might proceed.

**Comment by serundeputy** [comment]
@stpaultim I was able to replicate this.
thanks for your detailed STR.

I've filed a PR here https://github.com/backdrop/backdrop/pull/2431

testing script:

`config_set_core_update.php`:

```php
<?php    
    
config_set('installer.settings', 'core_update', 1); 
```

`tst3433.sh`:

```bash
#!/bin/bash    
set -ex    
set -ex    
    
git clone git@github.com:backdrop/backdrop.git 3433    
wget https://github.com/backdrop/backdrop/pull/2431.patch    
cp 2431.patch 3433/    
cp 3433.lando.yml 3433/.lando.yml    
cp config_set_core_update.php 3433/    
cd 3433/    
git checkout 1.11.0    
git apply 2431.patch    
lando start && lando drush si --db-url=mysql://backdrop:backdrop@database/backdrop
lando drush scr config_set_core_update.php    
lando drush uli
```

**Comment by jenlampton** [comment]
@serundeputy I've closed [the PR](https://github.com/backdrop/backdrop/pull/2431) because there was no matching issue explaining what the problem was, or how it could/should be fixed. There were also some syntax issues. Please push to a new branch when those issues are resolved so it's in a state that's ready for someone to review. I think we need to get that in before https://github.com/backdrop/backdrop-issues/issues/3271.

@stpaultim If you are not using PHP 5.6, then it is safe to try [the PR](https://github.com/backdrop/backdrop/pull/2431) as-is, and please let us know if it fixes your problem!

**Comment by laryn** [comment]
I think this one can be closed since it's easy to test via the UI now and separate issues would be raised for any issues found.
