### ISSUE TITLE
Be able to set a default region in flexible layout templates

### ISSUE THREAD

**Issue by herbdool** [backdrop/backdrop-issues#4024]
Layouts have default regions. But when creating a flexible template there is no option to set a default region. The default is useful when changing templates so any orphaned blocks can be moved to that default. There might be other features too, not sure.

I've tentatively marked it as a bug, since a layout template should probably have a default even though it seems to work without one.

---

PR: https://github.com/backdrop/backdrop/pull/2883

Current state of PR:
* Setting a default region in the template doesn't affect the reassigned blocks when switching templates. It's still putting all the blocks in the last region.
* Needs tests for default region

**Comment by laryn** [comment]
Since it is technically possible on a flexible template that someone deletes the row that has the default region, I suppose checking that the row doesn't contain the default region before allowing them to delete it makes sense?

**Comment by herbdool** [comment]
That would be useful too. Though not a guarantee since someone could import the config.

**Comment by docwilmot** [comment]
I considered that, but didnt bother. Could be wrong.

The main purpose of the default region is that the "main content block" gets placed there automatically  if a layout overrides a system path. This is fine for a fixed layout template but as you note, the system would need to have some way of picking which region is default. How? a checkbox on *every* row configuration form saying "region #x is default"? Then we'd need validation to make sure only one region is default. Or a checkbox below the flexible drag/drop UI? Nothing seems elegant.

But it seems there is no need for that, because a user who knows to select a default region would probably know just to add the "main content block" to the layout anyway, plus we'd be complicating the UI when only templates overriding system paths would benefit. In fact believe as well if you override a system path and dont place that block, Backdrop warns you anyway.

In all, I think it's not worth it. Maybe we should firm up that warning so that *any* template, flexible or not, thats used in the Default Layout must have a default region (that might already exist, not sure).

I think for the purpose of orphaned blocks, putting them into the last region seems reasonable enough.

**Comment by jenlampton** [comment]
I've posted a PR here for review, would love @docwilmot's eyes on it to make sure I am not missing anything.

**Comment by stpaultim** [comment]
Re: https://github.com/backdrop/backdrop/pull/2883

If you designate a region as the default region and then try to delete that region, the behavior is a little weird. It just doesn't do anything. Doesn't give you any feedback. Feels broken.

**Comment by jenlampton** [comment]
Hm. On my site you get the error message:
<img width="1316" alt="Screen Shot 2019-09-15 at 5 04 19 PM" src="https://user-images.githubusercontent.com/397895/64929433-e701ad80-d7da-11e9-9e4d-6c507767e0ca.png">

**Comment by jenlampton** [comment]
I see the same thing on the sandbox: 
<img width="1316" alt="Screen Shot 2019-09-15 at 5 04 19 PM" src="https://user-images.githubusercontent.com/397895/64929459-5a0b2400-d7db-11e9-81cc-bd0b1b82e691.png">

**Comment by herbdool** [comment]
Setting a default region in the template doesn't affect the reassigned blocks when switching templates. It's still putting all the blocks in the last region.

Also there's an error in the tests. Need to set `$default_region` so it's not being undefined sometimes.

@jenlampton

**Comment by herbdool** [comment]
Also, when I change the number of regions in a row it doesn't give a warning if the default region disappears. @jenlampton

**Comment by jenlampton** [comment]
Okay I've fixed the tests and added a row warning. But I have not actually made the default region setting be the default region. @quicksketch says that will need tests, and we may not have time for that tonight, so I'm going to move on to other issues. Putting a PR summary in the top issue if someone else wants to give it ago.

**Comment by stpaultim** [comment]
It looks like the problem when I tried to delete the row was that I could not see the top of the page and the warning message was at the top of the page. 

As a user, it was not clear to me that anything had happened. It did not take me to the top of the page to see the warning. I had the sense that nothing was happening. 

I am not sure if it is usual to automatically take the user to the top of the page when an error message is generated, but I think I expected that.

**Comment by quicksketch** [comment]
Let's move this to be post 1.14.0 release. It's still a bug but not a show-stopper.

**Comment by jenlampton** [comment]
I've updated the PR so it now actually uses the default region assigned in the UI.

**Comment by stpaultim** [comment]
Testing this today. Here are my notes.

1) If you add a new region it is not available to use as default until you save it first. Is this a problem. It's not ideal, but might be difficult or impossible to fix this. Help text might make situation better. I think most people will figure out that they need to save first. 

2) I still don't like the fact that when you try to delete a row that has the default region, if the error message is off the page the behavior seems very strange. But, it sounds like that should be a new issue.

**Comment by indigoxela** [comment]
What would be the correct labels for this issue? The current combination is a bit confusing.

Reading the issue comments, especially the latest, makes me think that "needs work" is the right one here.

**Comment by klonos** [comment]
Re earlier mentions of the issue about not seeing any errors and then thinking that nothing happened, that is a UX issue, and we have #1040 to address it (that issue is specific to form elements though, so we'd need to also consider the various layout configuration UIs when addressing it).

@jenlampton instead of an error message asking the user to select a new default region, how about we select the last region as the new default for them, and we then show a warning. So instead of this:

> Your default region has been deleted, Please select a new one.

...something like this?:

> The region %region_name which was the default region for this layout template has been deleted. The %last_region_name region has been set as the new default. Feel free to select another.

I like that approach better, because if the default region is not important for the site admin, then there's one less thing for them to do 😉
