### ISSUE TITLE
[UX] Better layout conditions display.

### ISSUE THREAD

**Issue by tarekdj** [backdrop/backdrop-issues#578]
A before/after preview:
![image](https://cloud.githubusercontent.com/assets/540268/5755769/c05ba036-9ca8-11e4-8897-a1f83367510b.png)

Patch ready but issue needs validation before sending PR.

---
~~PR by @tarekdj: https://github.com/backdrop/backdrop/pull/684~~
PR by @BWPanda: https://github.com/backdrop/backdrop/pull/2685

**Comment by BWPanda** [comment]
I like it, but what about merging the Configure & Remove links into the one dropdown (like everywhere else in Backdrop)?

**Comment by klonos** [comment]
Definitely much better. Thanx Tarek!

**Comment by tarekdj** [comment]
PR: https://github.com/backdrop/backdrop/pull/684

**Comment by quicksketch** [comment]
This looked great at the time and I'm sorry it took me so long to review it. Since then, we added the new Admin theme to Backdrop in 1.1, so the styling doesn't quite jive:

![screenshot18](https://cloud.githubusercontent.com/assets/100206/9833488/af9f2f6e-5955-11e5-9dce-cd25d5b341f3.png)

I'd like to see a couple of things:

- I think using drop buttons like @BWPanda suggested is a good idea.
- These styles should be moved to layout.admin.css if we want them to affect all themes (and I think we do).
- If we want Seven-specific styling (such as increased padding or borders) then that should be added to seven/style.css separately.

**Comment by docwilmot** [comment]
@tarekdj @BWPanda are you available to refresh this?

**Comment by klonos** [comment]
To add to the list of things that @quicksketch has put together above, also move the "+ add visibility condition" link above the list of conditions. But that task already has its own issue (#1547).

**Comment by tarekdj** [comment]
What about this ?
![preview](https://cloud.githubusercontent.com/assets/540268/13123274/bc04aa08-d5bb-11e5-8f0d-6915f2b50274.png)

**Comment by klonos** [comment]
Yes, now all that's left according to @quicksketch's list is to put the action links ("Configure" & "Remove") in a drop button (plus moving the css to appropriate places if you haven't done that already).

Another minor thing would be to apply zebra coloring to the list of conditions (one row white, one gray alternating).

**Comment by tarekdj** [comment]
Never worked with dropbutton any example code ?

**Comment by docwilmot** [comment]
[Links button for layout UI](https://api.backdropcms.org/api/backdrop/core%21modules%21layout%21plugins%21renderers%21layout_renderer_editor.inc/function/LayoutRendererEditor%3A%3AgetRegionLinks/1) is a good example.

**Comment by tarekdj** [comment]
Thanks @docwilmot I'll give it a spin this weekend.

**Comment by docwilmot** [comment]
Actually, you will find that those links ("Configure" and "Remove") are not links at all, theyre form buttons made to look like links using JQuery, so you wont be able to get them into dropbuttons.

**Comment by tarekdj** [comment]
@docwilmot : Thanks for the tip ;)
I already seen that. I made a good progress on it. A PR should be ready by tomorrow.

**Comment by tarekdj** [comment]
I started a new PR https://github.com/backdrop/backdrop/pull/1266
Anyone with good css skills is welcome to help me fix this https://github.com/backdrop/backdrop/pull/1266#issuecomment-186850675

**Comment by tarekdj** [comment]
@quicksketch @docwilmot , are you OK if I convert conditions output from list to table? This will make my life easier :)

**Comment by quicksketch** [comment]
> Actually, you will find that those links ("Configure" and "Remove") are not links at all, theyre form buttons made to look like links using JQuery, so you wont be able to get them into dropbuttons.

Good point. We can forgo the drop buttons if needed.

> are you OK if I convert conditions output from list to table?

I think we'd like to avoid tables if at all possible.

**Comment by klonos** [comment]
> We can forgo the drop buttons if needed.

:+1: I don't mind if we leave this as a follow-up issue for when we have the energy to implement it "the right way". ...plus I kinda secretly hate drop buttons when they have only two options. An unnecessary extra click for the users if you ask me. I think that we should only be converting links to drop buttons when there's 3+ options. But that's a whole different story.

**Comment by docwilmot** [comment]
Actually I think leaving out the drop buttons *is* the right way in this situation.

**Comment by BWPanda** [comment]
Revitalising this issue with a new PR: https://github.com/backdrop/backdrop/pull/2685

Here's the before & after:

![before_after](https://user-images.githubusercontent.com/2385329/57909979-cd804180-788c-11e9-9fe9-3533f23910b4.jpg)
(the yellow shows the hover state)

I basically copied the styling as much as possible from the 'Filter processing order' table, and I tried to put the appropriate styles in the appropriate places (e.g. layout module, seven theme).

**Comment by herbdool** [comment]
RTBC

**Comment by klonos** [comment]
A few comments:

- Should that table have a header with "Condition" and "Operations" columns?
- The order of configure/remove links changes on normal vs mobile.
- Those `float`s do not work particularly good on mobile + RTL:

   <img width="515" alt="Screen Shot 2019-05-19 at 12 38 41 pm" src="https://user-images.githubusercontent.com/2423362/57977075-491bf300-7a33-11e9-97ba-2696455eb92b.png">

**Comment by BWPanda** [comment]
So it's not actually a table, just the same un-ordered list as before, but styled to look like a table. Therefore I don't think it's possible/easy to add column headings since that would mean changing the HTML output, whereas everything achieved so far is just CSS... Also, the 'Filter processing order' table that I based this design off (which *is* actually a table) doesn't have column headings either:
![image (3)](https://user-images.githubusercontent.com/2385329/57979332-081ce200-7a25-11e9-9a38-26c5b27935ad.png)

I've updated the PR with flex instead of floats which seems to work better, for both the ordering of the links and RTL languages too.

**Comment by klonos** [comment]
Hmmm, still not good. Screenshots from progressively narrower screen:

![Screen Shot 2019-05-19 at 7 10 36 pm](https://user-images.githubusercontent.com/2423362/57980116-2d800f00-7a6a-11e9-95ea-e7942af78a40.png)

![Screen Shot 2019-05-19 at 7 10 45 pm](https://user-images.githubusercontent.com/2423362/57980125-3670e080-7a6a-11e9-9039-91d283b17f38.png)

![Screen Shot 2019-05-19 at 7 10 59 pm](https://user-images.githubusercontent.com/2423362/57980127-3a046780-7a6a-11e9-9c37-4db642fc9b69.png)

![Screen Shot 2019-05-19 at 7 11 11 pm](https://user-images.githubusercontent.com/2423362/57980129-3d97ee80-7a6a-11e9-80d0-3a400b0e37bc.png)

We need to also decide if we care about IE support for `display: flex` or not ([not good even on IE11](https://caniuse.com/#search=flex)) ...with the global usage of IE versions up to IE11 now dropped bellow 2.5%, you know how I feel about it 😄 (but that's a topic for #214).

**Comment by BWPanda** [comment]
What's not good? The full stop looks to be a wider issue, considering the other text on the page, and I figured wrapping was the best way to make it responsive, same as the way it is currently with the un-ordered list...

Suggestions to make it look better?

**Comment by klonos** [comment]
> What's not good? The full stop looks to be a wider issue...

Yeah, don't get me started on RTL and punctuation 😓 ...what is not that good is the breakpoint where the remove/configure links are "separated" from each other. These are meant to be a set.

> Suggestions to make it look better?

I have no good suggestions at this point; just a couple of thoughts:

- make these links a dropbutton
- make the output a table, and have the links live in a separate column

**Comment by klonos** [comment]
> - make these links a dropbutton

...re-reading the comments in this issue, I see that you had suggested the same back in 2015 @BWPanda

**Comment by BWPanda** [comment]
But then he changed his mind, and also said to avoid tables... https://github.com/backdrop/backdrop-issues/issues/578#issuecomment-187467461

**Comment by klonos** [comment]
...yeah, and almost everyone else seemed to agree that that is not a good idea 😓

**Comment by BWPanda** [comment]
I think a markup change is needed then, and I guess the easiest would be to wrap the two links together, then they'll stay together when wrapping.

**Comment by klonos** [comment]
> ...I guess the easiest would be to wrap the two links together, then they'll stay together when wrapping.

Yeah, I guess that'd be "safer" than using `flex` etc.

**Comment by BWPanda** [comment]
I still meant to use flex, but now that you mention it, I guess wrapping the links would fix the issue with using floats too, so I'll try that instead. Having said that, I'm pretty sure the layout icons/images at the top of this page use flex, which is why I tried it here too...

**Comment by BWPanda** [comment]
Ok, PR updated to add a wrapper to the operations links, and went back to using a float (rather than flex). @klonos can you re-test?

**Comment by klonos** [comment]
Yep, adding the wrapper makes it so that the "remove"/"configure" links are kept together as the screen width changes 👍 

I am going to change this back to RTBC, since the concerns/comments I had when I removed that label have been addressed (as best as possible at least). If others have other comments/suggestions, feel free to move back to NW.

**Comment by klonos** [comment]
...and as usual, this is a UX task, so proposing the next bug release milestone.

**Comment by quicksketch** [comment]
Thanks! https://github.com/backdrop/backdrop/pull/2685 merged into 1.x and 1.13.x.
