### ISSUE TITLE
[UX] Add parent menu selector to menu add/edit link form

### ISSUE THREAD

**Issue by bugfolder** [backdrop/backdrop-issues#6390]
## Description of the need

Currently, when you add a link to a menu via /admin/structure/menu/manage/menu_name/add?langcode=und, you choose the parent link via a drop-down selector, whose options include every possible parent link, including links in other menus.

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/b591210b-7188-4827-a96a-7dbe5e3fcf62)
Since you've just gone to this page to add/edit a link to/in this specific menu, it seems a bit odd to list links from all the other menus, too. "If I wanted to add a link to a different menu, I would have used 'add link' for that menu."

But there's a bigger problem if there are many menus; it's easy to get lost in the giant list when you're scrolling through a big menu. The admin bar alone adds lots of items to the select menu. For example, here's what the drop-down looks like when you're editing a link in the Account menu, which contains only two items:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/54e62dce-2599-4d9e-b440-98db3f4e1416)

On one of my sites, the organization has one or two events a year, and we create a new menu for each event for visitors to navigate through that event's pages (anywhere from 5 to 40 pages, i.e., 5 to 40 new menu links per event). And we don't throw away past events. So after several years, we've built up about 25 menus, and something like 2000 menu links in that selector to contend with when we're building up the next menu. It's very easy to get lost (especially since many of the menu links have similar names from year to year).

To deal with this, I wrote a small custom module that adds a separate selector for the "Parent menu" to the menu add/edit link form, so that admins can first select the menu, and then the "Parent link" selector only displays candidate parent links from that particular menu. It looks like this:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/2b216c83-9a1f-450e-98db-44f5e132992c)

It was pretty simple to implement: a `hook_form_FORM_ID_alter()` instantiation, plus an ajax callback to update the "Parent link" selector when the "Parent menu" is changed.

It occurs to me that this might be desirable default behavior for these two forms for others who don't want or need to see every possible menu link in the drop-down when they're trying to add or edit a link in a specific menu.

There's a couple of ways I could proceed from here. I'd like to get some feedback from people on the possibilities.

1. Submit a PR to change the core behavior to add the "Parent menu" selector for everyone.

2. Offer it as an option in core, via a "Menu settings" configuration checkbox (at admin/structure/menu/settings). That way the default behavior wouldn't change, but people could turn it on (at least, if they know to go look for the setting).

3. Don't change core, just make it a contrib module. (Currently it's custom.)

I'm happy to do any of the above, but there's two drawbacks to making it a contrib module. First, it's a lot less discoverable. Second, in a contrib module, the alteration happens via a `hook_*_alter()`, so after the original form is fully built, which means that one is still constructing the list of all possible menu links before replacing it with the more narrowly targeted list—so, a bit inefficient.

What do people think? Is this worth putting into core? If folks are in favor, I'm happy to provide the PR.

**Comment by olafgrabienski** [comment]
Great idea! Using already (too) many menu related contrib modules, I'm in favor of a core integration. Personally, I'd prefer the new feature as an option.

That said, I'm wondering if the dialog becomes potentially confusing when people see two options with the same default value and similar labels, like this:

**Parent menu**
User menu

**Parent link**
User menu

First idea to improve the dialog: Call the "Parent menu" label just "Menu".

**Comment by bugfolder** [comment]
> I'm in favor of a core integration. Personally, I'd prefer the new feature as an option.

I've created a PR that implements it as an option (set on the admin/structure/menu/settings page). Here's an image of what it looks like when turned on. A few things to note:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/bec0a66d-3c46-4f14-8770-46c7e0072806)

* To avoid the weirdness of the default choice for link looking exactly like the menu name above, when this option is turned on, I add "(top level)" to the link selector to provide some differentiation.
* To make the setting discoverable, I've added a "Configure this selector" link to the description, which links to the settings page.
* There's an interesting side effect for the weight, whose range comes from the range of menu item weights. That control will switch between a number field (with an up/down mini-button) and a selection, depending on how large the range is (large ranges = number field, small ranges = selector). That was always the behavior, but previously, the range was always the range over all possible menus, and the gigantic Admininstration menu always blew it into number-field territory. Now, if you pick a small menu (like the Account menu), you'll get a selector.

@olafgrabienski, @argiepiano, please take a look and give me your suggestions! (And of course, anyone else.)

**Comment by klonos** [comment]
...also, can we please extend the scope of this to also add the same behavior in the "Menu settings" vertical tab of content types as well as the content edit form? (when more than one menu has been configured to be available for a content type)

**Comment by bugfolder** [comment]
> I'd like it to be the default and only option....

I personally would also lean this way, but we've received at least one other vote for "make it an option" (@olafgrabienski)  so it would be nice to get further input from others to establish consensus (or at least, majority).

Thanks for your review and comments! I've implemented one, gave reason for another, and queried back about a third. Of course if we make it the default/only behavior, I'll strip out the setting.

**Comment by bugfolder** [comment]
> ...also, can we please extend the scope of this to also add the same behavior in the "Menu settings" vertical tab of content types as well as the content edit form? (when more than one menu has been configured to be available for a content type)

It looks like the vertical tab of content types already has this behavior (or perhaps I'm misunderstanding what you're talking about). Here's the content type edit page with two menus selected, and only those two menus' items are being shown in the default parent link:

<img width="1121" alt="image" src="https://github.com/backdrop/backdrop-issues/assets/29214084/b1de3572-92ae-422d-b0fe-24ec284fd317">

And here's the content edit form, which shows the same thing:

![image](https://github.com/backdrop/backdrop-issues/assets/29214084/281bac6c-2368-4fa4-833b-8d4ef79c2ad6)

**Comment by olafgrabienski** [comment]
>> I'd like it to be the default and only option....

> I personally would also lean this way, but we've received at least one other vote for "make it an option"

Prefering the feature as an option was probably result of my first concern that the dialog could become confusing. Now, where this has already been adressed, I'm fine with the new feature as only behavior.

**Comment by bugfolder** [comment]
Option is removed. That also allowed tightening the code a bit, and I fixed a minor bug I'd overlooked.

**Comment by bugfolder** [comment]
Oops, lost a test case. Probably need to update the tests.

**Comment by klonos** [comment]
> ...or perhaps I'm misunderstanding what you're talking about ...

Yup, that 😅 ...perhaps I didn't provide enough information to make it clear. If you enable all checkboxes for all available menus, including the admin menu, then the parent menu selection becomes unwieldy again.

So OK, allowing content links to be added to the admin bar is an edge case, however I used the admin menu as an out-of-the-box example which is easy to test. You could generate a fresh, rather huge menu with devel (or a few smaller menus and enable all of them). Then the problem we are trying to solve here is present in the content type configuration form, as well as the content edit form.

>Prefering the feature as an option was probably result of my first concern that the dialog could become confusing. Now, where this has already been adressed, I'm fine with the new feature as only behavior.

> Option is removed.

Nice! ...code looks much cleaner now too 🙂 🙏🏼

I've replied in the PR.

**Comment by klonos** [comment]
Sure 👍🏼 ...I was just thinking/hoping that we could perhaps abstract some of the logic, since we will be doing the same thing. But I'm fine with the follow-up issue.

**Comment by bugfolder** [comment]
Working on #6392, I've discovered some things that could be improved here, so setting it back to "needs work" for the moment.

**Comment by bugfolder** [comment]
I've simplied the ajax, and also moved the appending of "(top level)" into the helper function so that other similar implementations can make use of it (like #6392). @klonos, I left a question back for you in the PR about replacing `'#prefix' => '<div id=...>'`with a `'#type' => 'container'` wrapper.

**Comment by klonos** [comment]
@bugfolder looks good, and I have replied to your question 👍🏼

**Comment by argiepiano** [comment]
An sidenote observation to the `#prefix` / `#suffix` discussion: changing this by using a wrapper changes the array structure of the $form variable, which may break existing form alter hooks in contrib (or in custom modules developed by site builders).  This was pointed out by @bugfolder  and I think it's a valid concern. While I agree that `#prefix ...` should be avoided, it's not a good idea to make this change in existing code that already used it.

**Comment by bugfolder** [comment]
> mitigating this concern is the fact that the PR does make changes to the array structure even before changing the `#prefix` use...

Yes. It's a little unfortunate. The most efficient way to implement the new behavior is to put everything that changes inside of a single `'#type' => 'container'` wrapper, and then the ajax can use the simplest `'callback'/'wrapper'` idiom. But, as you observe, that changes the `$form` array structure.

Safest would presumably be to preserve the existing `$form` elements and just add new elements or properties where needed. I'd done that in an earlier version of this PR, and it looks like I should go back to that way of doing things.

Even replacing the existing `'#prefix'/'#suffix'` with `'#wrapper_attributes'` in `$form['parent']` to get the `id` in place changes the HTML, so potentially breaks themes (the selector `#menu-parent-select-wrapper .form-item-parent` would no longer work, for example, since both end up in the same `div` with `#wrapper_attributes`). But we can use `'#wrapper_attributes'` on the new bits.

**Comment by klonos** [comment]
Right 🤔 😞 ...I guess we'll need to keep doing what I personally consider a hack for now, and I'll raise an issue to clean things up in Backdrop 2.x then 🤷🏼 

Thank you both for the feedback/insight @bugfolder and @argiepiano 🙏🏼

**Comment by stpaultim** [comment]
We looked at this issue/PR in the Design/UX meeting last week. The change looks good to me. Thanks for the work going into this issue.

**Comment by indigoxela** [comment]
As with all form structures in core, that change - we have to thoroughly consider backwards compatibility.

Both, hook_form_alter() and hook_form_FORM_ID_alter() implementations may be affected. We don't want to break things.

**Comment by indigoxela** [comment]
To revive this issue... We'd need a little more testing re form structure change and possible impact on existing contrib modules. Probably it's nothing, but better safe than sorry. :wink: 

Several modules implement alter hooks on the *menu_edit_item* form. Let's make sure, they don't break.
Here's a quick list of implementations, for further testing: https://github.com/search?q=org%3Abackdrop-contrib%20menu_edit_item&type=code

Additionally it seems, like the removal of function menu_update_parent_options_ajax() is premature, as it's still in use elsewhere.

**Comment by olafgrabienski** [comment]
> Several modules implement alter hooks on the menu_edit_item form. Let's make sure, they don't break.

I'm using _some_ of those modules, but I'm not sure what to look for to test them. Or does it however make more sense to ask the module maintainers?

**Comment by olafgrabienski** [comment]
@izmeez That could work somehow on real world sites: sooner or later some issues might come up, or not. I'd prefer to test with more specific ideas what to look for.

**Comment by stpaultim** [comment]
In Zulip @indigoxela asked why this one is stalled. From my review of the issue, it seems like momentum was stalled by this concern:

> To revive this issue... We'd need a little more testing re form structure change and possible impact on existing contrib modules. Probably it's nothing, but better safe than sorry. 😉
https://github.com/backdrop/backdrop-issues/issues/6390#issuecomment-2254027487

I've put this on the agenda for the next dev meeting to discuss whether or not the potential conflict with contrib is an issue and IF SO, how to get past it. 

Any thoughts?

**Comment by indigoxela** [comment]
> Any thoughts?

Testing would be a huge help. Whether there _is_ even a conflict with one of the contrib modules helps a lot for a decision, I guess. And I mean testing with the contrib modules, that implement an alter hook - the link in my previous comment should help to identify them.

And, of course, function menu_update_parent_options_ajax() should not get removed, yet - it's still in use in core.

**Comment by stpaultim** [comment]
This was discussed during meeting today starting at: https://www.youtube.com/live/O17yLvRozoM?si=7ROrs9HXd1oEN79d&t=2674

@quicksketch Did not think that this poses a significant risk to Backwards compatibility in Contrib. But, additional testing would still be useful. I've been a little unsure of what to test or how to test it most effeciently, but I suppose I could just try applying this to some sites with "menu" related contrib modules. I'll try to do that this weekend. 

I believe that there is also a comment on the PR that is unresolved. 

@bugfolder Any chance that you will have time this weekend to update this PR so that sandbox works?

**Comment by bugfolder** [comment]
> Any chance that you will have time this weekend to update this PR so that sandbox works?

Pretty tied up these days, but I'll try to put some time on it.

**Comment by stpaultim** [comment]
I'm going to rebase this PR, just so that we can have a sandbox and folks can test it.

**Comment by stpaultim** [comment]
I just created a new PR that should be a replica of the PR by @bugfolder. https://github.com/backdrop/backdrop/pull/4860

I'm probably not able to take over care of this PR, but wanted to at least give folks something they could test in a Sandbox to potentially move this issue forward.

Atten: @backdrop/core-committers

**Comment by bugfolder** [comment]
For reference: contrib modules that implement `hook_form_menu_edit_item_alter()` (via https://github.com/search?q=org%3Abackdrop-contrib%20form_menu_edit_item_alter&type=code, H/T to @indigoxela):

* menu_views
* menu_position
* content_menu
* special_menu_items
* menu_attributes
* i18n_menu
* menu_image
* menu_admin_per_menu
* xml_sitemap_menu
* menu_per_role
* menu_item_visibility
* menu_attach_block
* menu_position

Gonna try them out with the current (revised) PR. If there's other contrib modules to test against, please comment.

**Comment by bugfolder** [comment]
I did my first test against the [Content Menu](https://backdropcms.org/project/content_menu) module, and ran into a problem that may afflict multiple contrib modules. The Content Menu module moves some of the form settings, including the "Parent link" selector, into a fieldset titled "Advanced menu item settings" that appears below the Save/Delete buttons, like this. The incompatibility is that the newly added "Menu" selector is left behind (naturally, since the contrib module knows nothing about it).

![image](https://github.com/user-attachments/assets/19b608d9-b37d-4545-babd-353f355fb902)

There are also some problems with Javascript updating when this or that select item has been changed, which is somewhat complicated by the fact that there is an existing bug in the Content Menu module that manifests when multiple languages are enabled and installed (I've filed an issue at https://github.com/backdrop-contrib/content_menu/issues/3).

Even aside from the existing bug, there's really no clean way of getting the **Menu** select and the **Parent link** select to appear together, as one would like it to be. The fieldset is added via the module's `hook_..._alter()` implementation; so the module knows nothing about the Menu select, and core knows nothing about the fieldset.

The solution I came up with amounts to this: "If a contrib module is enabled that was expecting the old form structure, give it the old form structure." So there's a list of conflicting contrib modules that we check for enablement.

But what happens if the contrib module wants to make use of the new form in a future update? The solution I came up with—which feels a bit hacky, so I'm open to better-way suggestions—is to check for a "hidden" configuration setting in the module. If the module has a config value `use_updated_edit_menu_item` in its settings, then it gets the new form, so contrib modules that want the new form can set this value in an update hook in a future release. Otherwise, they'll continue to use the old form until they get around to updating. (Presumably in Backdrop 2.0, we'd drop the old form.)

The detection code looks like this:
```
  $legacy_modules = array('content_menu');
  $use_legacy_menus = FALSE;
  foreach ($legacy_modules as $legacy_module) {
    $use_legacy_menus |= (module_exists($legacy_module) && !config_get($legacy_module . '.settings', 'use_updated_edit_menu_item'));
  }
```

Currently, only `content_menu` gets this treatment, but I haven't yet checked the other contrib modules; probably others may go into that first array.

What do people think of this approach to contrib compatibility?

**Comment by bugfolder** [comment]
I've now looked at all the contrib modules that might be affected. Looks like `menu_views` needs a similar handling as `content_menu` (i.e., use the legacy form). Some modules I'm not sure of. Here's what I've found.

### content_menu

Maintainer: Al-Rozhkov

Quite incompatible. Use legacy setting.

### menu_views

Maintainer: Laryn

Not compatible. Like content_menu, it moves some form items into a fieldset and overrides the "Parent link" option (renamed to "Parent Item"), among other changes. Use legacy settings.

### menu_position

Maintainer: Laryn

No immediately obvious problems, but probably need to check with some realistic rules in place. Perhaps Laryn can test?

### special_menu_items

Maintainer: Laryn

Looks compatible.

### menu_attributes

Maintainers: quicksketch, klonos

Looks compatible.

### i18n_menu

Maintainers: indigoxela, docwilmot

Not sure. Perhaps indigoxela or docwilmot could test?

### menuimage

Since there's no releases, not gonna check.

### menu_admin_per_menu

Maintainer: jenlamption

Appears to work, since it just filters to the options provided by core.

### xmlsitemap_menu

Maintainers: quicksketch, Laryn

Compatible.

### menu_per_role

Maintainer: ericfg

Compatible.

### menu_item_visibility

Maintainer Robert Garrigos

Compatible.

### menu_attach_block

Maintainer: Alan Mels

Not sure. No blocks seem to be available in default installation. Perhaps Alan Mels can test?

### menu_firstchild

Maintainer: owenmorrill

Compatible.

### void_menu

Maintainer: William Hall

Compatible.

**Comment by stpaultim** [comment]
I don't have any answers here, but looking at this conflict - I'm guessing that this may take some discussion in a dev meeting to resolve.
https://forum.backdropcms.org/forum/dec-5th-weekly-dev-meeting

Unless @backdrop/core-committers get involved before then.

**Comment by indigoxela** [comment]
> What do people think of this approach to contrib compatibility?

Tricky, not sure - I'm glad that I don't have to decide... :grimacing:
This really looks like a topic for a discussion in the dev meeting.

**Comment by bugfolder** [comment]
> @bugfolder this is tricky. What happens if none of the "legacy modules" are used, how does someone use the updated form? 

If they don't use a legacy module, they get the updated form. ONLY users of the legacy module get the legacy version of the form.

(There is still a potential problem: what if module1 updates, but module2 doesn't? Then module1 would still get the old form, even though it's now expecting the new form.)

> And what about a custom module that needs to use the old form? Currently, does your hack handle that?

It doesn't currently, so that's a serious consideration. But the same question could be asked about ANY modification to core: what if a custom module relies on that particular tweak to core? I am somewhat heartened that of all the modules that explicitly create a `hook...alter()` implementation, only two were for-sure incompatible.

> I'm a bit leery of hard coding a list of contrib modules in core. 

Yeah, me too. On the other hand, once those modules have updated to use the new form, the hard-coded list and hack can be removed.

> I don't have a great alternative, though I wonder if we just have a setting in core where an admin switches back to default to the old form if they experience problems. 

That's a possibility. I would worry that if someone encounters the incompatibility (and they might not encounter it immediately, since it would only show up when they're adding/editing a menu item), they wouldn't know where to look to switch back t othe old form.

> And then also work with the module maintainers to make them compatible.

For sure! I couldn't think of a really good solution, so was falling back to the "least bad" solution, but welcome other contenders for "least bad" (even better, a "really good" solution!).

**Comment by indigoxela** [comment]
Two possible approaches come to my mind:

1. Put this functionality into a contrib module - to be merged into core in 2.x
2. Do not change form logic, instead create a JavaScript widget based on the old form structure

Assuming, that right now many people might consider Backdrop as alternative for their D7 site (under time pressure), it seems like the wrong signal to come up with a backwards incompatible change to menu item handling.

I'm still hoping, this improvement doesn't have to be incompatible, just have no time right now to dig deeper into this.

**Comment by bugfolder** [comment]
How about we make it a core menu setting, with the default of off (for B/C) and a note in the setting description that it "might be incompatible with other modules that alter the menu edit form"? That would make it more accessible/visible to admins ("Browsing the settings...hmmm, let's see what this does") than would putting it into contrib.

**Comment by herbdool** [comment]
@bugfolder that sounds like the least bad option.

So disabled by default. At least for existing installations. What do we want to do about new installs? Perhaps for new installs, it's less risky to just enable that setting by default, since they're more likely to download the latest version of the contrib modules.

**Comment by bugfolder** [comment]
> Perhaps for new installs, it's less risky to just enable that setting by default...

So perhaps the following:

* In the core config file, it's ON (for new from-scratch installs).
* In an upgrade hook (which won't run for new installs), it's turned OFF (for B/C).

**Comment by herbdool** [comment]
@bugfolder that sounds good. This is the approach which we've done for other new features as well. And then we can make sure the affected contrib modules are updated as well.

**Comment by stpaultim** [comment]
For what it's worth. The solution by @bugfolder sounds pretty reasonable to me.

**Comment by docwilmot** [comment]
> How about we make it a core menu setting

Put what exactly in the settings, though? I can't track what's the prevailing idea here, sorry.
I would also vote no to a list of contrib modules in core.
> Do not change form logic, instead create a JavaScript widget based on the old form structure

I also think a JS solution sounds right too. Use JS to put a menu select after/before the parent menu select, wherever it is. If the JS doesnt find the correct selector for the parent menu element, then nothing happens. That way any significant `form_alter` down the line that changes the form structure too much would just leave the form as it was.

**Comment by bugfolder** [comment]
> Put what exactly in the settings, though? I can't track what's the prevailing idea here, sorry.

Add a checkbox to admin/structure/menu/settings titled something like "Use separate menu select in menu item edit forms", with a bit more explanation in the description. If checked, use the separate menu select; if not checked, use the original form structure.

> I also think a JS solution sounds right too. Use JS to put a menu select after/before the parent menu select, wherever it is.

So I can see how one could use JS to move the HTML for the `parent_menu` select to the right place in the DOM. But there's also the AJAX that replaces various form element values with the content of elements of the `$form` array, and if a contrib modules has moved those elements of the `$form` array elsewhere within `$form` (like into a separate fieldset), the AJAX callback will have to figure out where in the PHP array it is hiding to get the value to update its corresponding HTML element. Seems like that could be complicated to do in a general way.

Example: suppose the user changes the `parent_menu` select value. Then the AJAX needs to update the `parent` options and value on-screen with new values that go with that new menu choice. But the contribution module's `...alter()` implementation has moved `$form['parent']` to `$form['advanced']['parent']`, so the AJAX callback needs to get the new values from there—without knowing where the contrib module moved that element.

And then, if (as in `menu_views` module), the contrib module has not just moved `$form['parent']` but has completely rewritten it in a way that ignores the new `'parent_menu'` form element, there's no possible way the AJAX can update the DOM correctly.

So I think the JS solution would be pretty hard.

**Comment by stpaultim** [comment]
<details><summary>What this current PR does - REVIEW</summary>

WAS:
![image](https://github.com/user-attachments/assets/0a16cff4-e6ac-4241-b3c3-19207ae8dc3c)

CURRENT PR:
![image](https://github.com/user-attachments/assets/4714e414-15a4-4ff2-bebc-75c231503249)

</details>

For the visual learners, this is the menu settings page where this option will go.

<details><summary>Menu Settings Page</summary>

![image](https://github.com/user-attachments/assets/8f9bd5c7-390a-4443-9ce7-17658c95a50b)

</details>

One suggestion for possible wording.

----

**[ ] Add option to select by Menu on menu edit forms**
_When creating a menu link, this allows you to sort parent links by individual menus, rather than a single long list of every link on site. Caution, may conflict with some menu related contrib modules._ 

----

I hesitate to suggest this, because no decision has been made on whether or not this solutions makes sense and it's extra work. BUT, it MIGHT be easier to get consensus on this option - if it was actually in PR and folks could try it OR at least provide a mock-up of the settings page with the config option in it.

**Comment by bugfolder** [comment]
Since there's general agreement that hard-coding a list of contrib modules is undesirable, I've gone with adding the config option in menu settings instead (per @stpaultim's comments above, and adopting a modification of his wording).

**Comment by herbdool** [comment]
@bugfolder thanks, that's looking better.

I've updated the PR branch from 1.x.

(Maybe we need a new issue to also add a separate menu selector for content types. I was just comparing and noticed that if a content type is set to have multiple menus available it also has an overwhelming list of menu items combined from all the menus which it has access to. Maybe this same setting could enable it on content types as well.)

**Comment by bugfolder** [comment]
> Maybe we need a new issue to also add a separate menu selector for content types. 

Yeah, that's https://github.com/backdrop/backdrop-issues/issues/6392. I expect a similar solution there would apply (subject to the same config checkbox in menu settings, if that's what we end up with here).

**Comment by docwilmot** [comment]
I've posted a rough draft PR of how this could work with just JS. We look for the Menu links select wherever it is and tack on the Menu select before it. Works with Content Menu, havent tested with anything else.

**Comment by bugfolder** [comment]
> havent tested with anything else.

Hmm, I applied the patch 4913.diff to core, but it doesn't seem to be showing only the links of the selected menu. The "Parent links" item still shows all menu links of all menus. (This is with core only, no contrib modules enabled.)

It would also be worth checking both `content_menu` and  `menu_views` module compatibility, since the latter module actually rewrites part of the `$form` as part of its alterations.

**Comment by docwilmot** [comment]
Strange, it works fine on the sandbox. Note (still needs work) when you first load the menu item edit page, you need to actually select a different menu so the JS kicks in, to test. Final version could probably add an "All menus" selection and have that default on first page load.

**Comment by bugfolder** [comment]
Yeah, it didn't work on first appearance, but does work after selecting a menu. Tentatively, nice!

Seems to still be incompatible with core Language+Locale module. Install a second language, then go edit a link and change the language. The Menu select vanishes.

**Comment by bugfolder** [comment]
Also, when editing an existing menu link, when the form is first brought up, it not only lists all possible menu items in the "Parent link" select, but also lists the wrong menu in the "Menu" select.

**Comment by docwilmot** [comment]
> Both have the same cause though: AJAX reloads cause the element ID to increment, like to parent-menu--2 or such. Fixable by using a data- element as a selector instead.

This is bogus info though. Turns out that the language AJAX issue can be fixed despite this. Also it looks like any new form element added to the core `menu_edit_item()` function will be removed by `menu_views`.

Coincidentally I think there's a bug with `content_menu` and Language?? Even without this PR if you switch language with that module enabled the menu select seems to disappear.

So it seems the only contrib this wont add new functionality to will be `menu_views`. But this was my point in suggesting a JS solution anyway, because if any contrib messes too much with the form structure, the form will just fall back to what exists now. Contrib can then make changes to suit the new menu limiter.
> Also, when editing an existing menu link, when the form is first brought up, it not only lists all possible menu items in the "Parent link" select, but also lists the wrong menu in the "Menu" select.

Yeah I did mention we can fix defaults, if this solution seems OK to everyone, can work on it.

**Comment by bugfolder** [comment]
> Coincidentally I think there's a bug with content_menu and Language?? Even without this PR if you switch language with that module enabled the menu select seems to disappear.

Yes, that would be https://github.com/backdrop-contrib/content_menu/issues/3, mentioned above.

> if this solution seems OK to everyone, can work on it.

Your approach looks pretty neat to me. I'm in favor of continuing down that path.

**Comment by docwilmot** [comment]
> Also, when editing an existing menu link, when the form is first brought up, it not only lists all possible menu items in the "Parent link" select, but also lists the wrong menu in the "Menu" select.

Brings up the right menu on first load  now, but still lists all possible menus; did we want to change that? Would people maybe be used to having all menus listed? This might be a silly question given the whole point of this issue, but thought I'd ask it to be sure before we change the default behavior.

**Comment by indigoxela** [comment]
> Brings up the right menu on first load now, but still lists all possible menus; did we want to change that?

I'd like to have all enabled menus available - because, how would I move an item to a different menu otherwise?
As possible parents only those available in the currently selected menu, if that's possible. And possible parents should follow the selected menu, ideally. (Sorry if I missed the point, I didn't actually test the new approach, yet.)

**Comment by stpaultim** [comment]
I'm a bit confused about the status of this issue. This is the current situation as I understand it. 

1. The decision has been made to go with the PR by @docwilmot 
2. There is some discussion about whether or not the PR should list all possible menus. But, I am not seeing anyone advocate for that. 

![image](https://github.com/user-attachments/assets/4c62bfbb-ab8b-4a35-8ef5-d2b044cda209)

![image](https://github.com/user-attachments/assets/d1f0824a-05d9-4d54-bda7-4013b96f5ce8)

This all looks like a nice improvement to me. Is the next step getting a code review?

**Comment by docwilmot** [comment]
Yes, I did address all issues, awaiting code review.

**Comment by stpaultim** [comment]
This was discussed briefly at the DEV meeting last week. Not much was resolved or decided. @quicksketch said he needed more time to think about this. 
https://www.youtube.com/live/VRHIfFzfhn0?si=PVSYLsNAHKTiOYHD&t=943

**Comment by stpaultim** [comment]
> Works with Content Menu, havent tested with anything else. https://github.com/backdrop/backdrop-issues/issues/6390#issuecomment-2502441466
> Yes, I did address all issues, awaiting code review. https://github.com/backdrop/backdrop-issues/issues/6390#issuecomment-2533423547

Does this need additional testing with contrib modules? (Atten: @docwilmot or @bugfolder)

**Comment by quicksketch** [comment]
I've code reviewed the current PR see https://github.com/backdrop/backdrop/pull/4913#pullrequestreview-2498081620, but like @stpaultim, I'm not sure if the current approach needs testing with contrib or not. I like that the current PR doesn't require any additional configuration options though. Is that because they're no longer needed, because this is contrib-compatible?

**Comment by docwilmot** [comment]
Testing with contrib so far:
- menu_views - no effect (which means works same as before)
- menu_position - works
- content_menu - works
- special_menu_items - works
- menu_attributes - works
- i18n_menu (part of i18n) - works* (but I may not be well versed with this module)
- menu_admin_per_menu - doesn't work; module gives access to some menus but gives no to access to `admin/structure/menu/parents` (that pathstill requires `administer menus` perms) This PR accesses that path in JS, so its broken.

**Comment by docwilmot** [comment]
> but like @stpaultim, I'm not sure if the current approach needs testing with contrib or not. I like that the current PR doesn't require any additional configuration options though. Is that because they're no longer needed, because this is contrib-compatible?

The thinking was this is built so that if the JS fails, things go back to how they are now anyway, so no need for a setting. This sounded like a valid answer, but if anyone thinks a setting would be more secure, then I'd be happy to add it.

**Comment by quicksketch** [comment]
The code looks acceptable to me. It could be more code-style compliant but we'd have to refactor the whole file. As-is, it's consistent with the existing code.

@bugfolder Could you give this an additional testing/review and see if it meets your expectations and if you would anticipate it causing any problems?

**Comment by indigoxela** [comment]
@docwilmot one last thing (ajaxComplete()), then this should be ready to go. See my PR comment for more info.

I really love this, it's a real improvement! :heart_eyes:

**Comment by herbdool** [comment]
I can confirm that this works `content_menu` and `menu_views` (the latter just fallsback to the current behaviour which is fine). Those were the two which were had the most concern, as noted above in the thread.

**Comment by herbdool** [comment]
I changed the `ajaxComplete` issue and removed the needs work label.

**Comment by bugfolder** [comment]
> Could you give this an additional testing/review and see if it meets your expectations and if you would anticipate it causing any problems?

I've tried it out, works like a charm. Color me impressed with @docwilmot's JS-fu. (Also color me LGTM, WFM, and RTBC.)

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop/backdrop/pull/4913 into 1.x for 1.30.0! Great work @docwilmot, @bugfolder, @herbdool, @olafgrabienski, @klonos, @argiepiano, @indigoxela, @stpaultim, @laryn, and @izmeez!
